### ISSUE TITLE
关于ONNX调用的问题

### ISSUE THREAD

**Issue by Olalaye** [ppogg/YOLOv5-Lite#1]
我在[链接](https://mp.weixin.qq.com/s/pADxO_RDGP9GZG2tuoi0ug)看到了你这个项目。有些地方不太明白，想请教一下：
文章的`五、What can be used for？`中有两个地方：
>（G2）导出onnx后无需其他修改（针对部署而言）
>（G3）DNN或ort调用不再需要额外对Focus层进行拼接（之前玩yolov5在这里卡了很久，虽然能调用但精度也下降挺多）
这个是指yolov5原代码的模型导出onnx即可使用DNN和ort直接调用吗，还是经过你的修改之后才可以

**Comment by ppogg** [comment]
是的先生,首先第一条:
（G2）导出onnx后无需其他修改（针对部署而言）
请参考[https://zhuanlan.zhihu.com/p/275989233](https://zhuanlan.zhihu.com/p/275989233),如果不摘除Focus,一般在大多数的向前推理框架都需要添加对focus层的额外修改或支持,举个例子,比如ncnn这个框架,是这样的:
![image](https://user-images.githubusercontent.com/82716366/130002547-8d0b76dc-4f39-4e88-a07d-8eff7aefbced.png)
接着针对第二条:
提取的onnx文件如果你需要使用ort或者dnn进行调用,也需要进行额外的contract拼接,详见链接:
[https://blog.csdn.net/qq_30263737/article/details/114392763](https://blog.csdn.net/qq_30263737/article/details/114392763)
![image](https://user-images.githubusercontent.com/82716366/130002836-20b34fd5-cb7e-4755-b205-cf90f906781d.png)
以及[https://blog.csdn.net/weixin_41868104/article/details/115614586?ops_request_misc=&request_id=&biz_id=102&utm_term=dnn%E8%B0%83%E7%94%A8yolov5&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-6-.nonecase&spm=1018.2226.3001.4187](https://blog.csdn.net/weixin_41868104/article/details/115614586?ops_request_misc=&request_id=&biz_id=102&utm_term=dnn%E8%B0%83%E7%94%A8yolov5&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-6-.nonecase&spm=1018.2226.3001.4187)
![image](https://user-images.githubusercontent.com/82716366/130002984-04773420-9116-48a4-8d30-b7c8480e2527.png)
另外,你可以试下我的另一个仓库[https://github.com/ppogg/YOLO-Streaming](https://github.com/ppogg/YOLO-Streaming):,里面有对yolov3,yolov4,yolov5,yolox的各种dnn和ort调用:
![image](https://user-images.githubusercontent.com/82716366/130003234-7ced37ca-7d4f-454d-ab29-df0574a2bdf2.png)
但是你会发现,使用dnn调用原来的yolov5.onnx会出现精度严重下降的情况,这是没办法的事
以上,希望能解答你的疑惑~
