### ISSUE TITLE
测试帧率问题

### ISSUE THREAD

**Issue by luckywangchenxi** [ppogg/YOLOv5-Lite#10]
您好，复现shufflev2-yolov5代码与官方yolov5s代码对比，在同一实验环境下测试同一段视频为何测试速度反而是yolov5s更快一些（测试了两次）。

shufflev2-yolov5 | yolov5s
------------ | -------------
96.353s | 92.874s
95.978s | 90.501s

**Comment by ppogg** [comment]
麻烦朋友告诉一下你测试时的硬件设备信息:比如架构是x86,使用GPU,显卡是多少这些~

**Comment by wangchenxi777** [comment]
系统：Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-80-generic x86_64)
显卡：TIAN V 
conda环境如下：
![图片](https://user-images.githubusercontent.com/58254947/130715260-c317d3c3-0ce4-4849-bf72-de06c041d820.png)

**Comment by ppogg** [comment]
噢，我知道为什么了，shufflenet和mobilenet设计之初是为了适配芯片或者端侧设备，但是如果你使用GPU来跑这些网络或者包含这些boacbone的检测网络，效率会及其的慢，这主要是涉及到一个吞吐量和缓存的问题，在不同硬件设备上的推理时长我已进行过测试：
![image](https://user-images.githubusercontent.com/82716366/130736571-498926b6-9c31-4f46-9c2a-563c4e723ba5.png)

另外，如果朋友你想更加深入了解之所以会慢的原因，这里有一篇博客，讲的特别好：
[为什么 MobileNet、ShuffleNet 在理论上速度很快，工程上并没有特别大的提升？](https://www.zhihu.com/question/343343895/answer/816049923)

**Comment by ppogg** [comment]
如果你是学生，准备发论文的话，你可以尝试将你的视频在芯片上或这旧手机端进行检测，会有一个非常大的差距对比

**Comment by wangchenxi777** [comment]
好的，谢谢您的建议

**Comment by ppogg** [comment]
不客气，后期会尝试使用repvgg进行backbone的替换，同时兼容cpu和gpu，你可以持续关注这个repo，不定时更新

**Comment by wangchenxi777** [comment]
好的，一定
