### ISSUE TITLE
MNN performance much less than NCNN

### ISSUE THREAD

**Issue by bl6g6** [ppogg/YOLOv5-Lite#102]
Hi, has anybody met the problem that MNN has less performance than NCNN？ Like the confidence and mAP? I printed out the outputs of NCNN and MNN in terms of the same image, but their outputs differ a lot. The confidences of MNN are almost all lower than NCNN, and bboxs are worse as well. 
Another question is that my input size of an image is 320 * 240, but the model input size is 320 * 256. Is that reasonable?

**Comment by ppogg** [comment]
朋友你好，你说的性能差是指误检多还是漏检多呢，能否将类似的结果贴一下呢？

**Comment by bl6g6** [comment]
> 朋友你好，你说的性能差是指误检多还是漏检多呢，能否将类似的结果贴一下呢？

作者你好，比如一张测试图，MNN上相比NCNN预测的置信度整体变低，而且整体框的iou也变小（框不准），感觉像是一个很差的模型。我是用的灰度图所以改成了单通道。然后因为模型是320*256的input，所以我的inputsize也改成inputsize_h, inputsize_w，不然会出现segmentation default。

**Comment by ppogg** [comment]
好的，是使用了int4量化是吗？

**Comment by bl6g6** [comment]
> 好的，是v5lite-s使用了int4量化是吗？
同一个模型，没做量化

**Comment by ppogg** [comment]
好的，能否试一下三通道的测试结果，检测结果差和输入尺寸关系不大，应该是其他方面的原因，比如读入的图片是rgb或者bgr，或者gray，这些问题经常会遇到

**Comment by bl6g6** [comment]
> 好的，能否试一下三通道的测试结果，检测结果差和输入尺寸关系不大，应该是其他方面的原因，比如读入的图片是rgb或者bgr，或者gray，这些问题经常会遇到

收到 感谢

**Comment by bl6g6** [comment]
最后定位问题是export成onnx的时候image size写成320 * 240了，我理解成我数据集的图片大小了，改成320 * 320以后model input size就是320 * 320了，然后输出结果MNN和NCNN相差无几。
