### ISSUE TITLE
coco数据集上测试检测不到目标是什么原因呢

### ISSUE THREAD

**Issue by raychiu0202** [ppogg/YOLOv5-Lite#103]
[ncnn-fp16.zip](https://github.com/ppogg/YOLOv5-Lite/files/7894625/ncnn-fp16.zip)
这里是我的yolov5.cpp和yolov5s_6.0.param文件，模型我用的是您ncnn编译好的fp16的Lites模型，其实我按照您的博文来检查，发现只需要改动yolov5.cpp对应Permute层后处理的两处，其他地方您都是修改好的，但是最终我在coco数据集上测试检测不到目标。

**Comment by ppogg** [comment]
ncnn的版本号是多少？

**Comment by raychiu0202** [comment]
> ncnn的版本号是多少？

git clone的最新的版本

**Comment by ppogg** [comment]
好的，20210525的版本试试

**Comment by ppogg** [comment]
另外，请使用这个连接的模型：
https://pan.baidu.com/share/init?surl=kWtwx1C0OTTxbwqJyIyXWg

**Comment by raychiu0202** [comment]
> 另外，请使用这个连接的模型： https://pan.baidu.com/share/init?surl=kWtwx1C0OTTxbwqJyIyXWg

我用的就是这个模型，然后刚才重新clone的20210525 tag的ncnn测试还是检测不到东西，我那两个文件param和bin配置的对吗？目前不知道原因在哪里。

**Comment by ppogg** [comment]
https://drive.google.com/drive/folders/1w4mThJmqjhT1deIXMQAQ5xjWI3JNyzUl?usp=sharing
请试一下这个
