### ISSUE TITLE
Error after convert onxx 

### ISSUE THREAD

**Issue by NTHoang99** [ppogg/YOLOv5-Lite#104]
I got this error 
![image](https://user-images.githubusercontent.com/48252530/150391384-c281deff-db7b-4bfd-9d91-ea71f0058eef.png)
This is my onnx file after train yolov5-lite s : https://drive.google.com/file/d/1x9hkc3bQjxybIucJEMXwoKeQ-kR3OZma/view?usp=sharing, Can you help me convert to bin and param file to use for deploying on android ? tks

**Comment by ppogg** [comment]
Did you export using the yolov5-6.0?

**Comment by NTHoang99** [comment]
> Did you export using the yolov5-6.0?
i used this:
https://convertmodel.com/
