### ISSUE TITLE
您好，1x1 conv支路，并不会为网络带来提升，反而下降了

### ISSUE THREAD

**Issue by beauty-snowman** [ppogg/YOLOv5-Lite#105]
这是为什么呀

**Comment by ppogg** [comment]
Hi，已收到，麻烦贴一下你复现的代码以及yaml文件，review一下

**Comment by ppogg** [comment]
重参化问题：
https://github.com/ppogg/YOLOv5-Lite/issues/64#issuecomment-1015295993

**Comment by ppogg** [comment]
该问题长期未更新，将关闭。
另外，请不要使用本仓库的部分代码粘贴到YOLOv5-6.0中，存在不兼容负优化的现象，谢谢！
