### ISSUE TITLE
efficientnet-lite0 model bug

### ISSUE THREAD

**Issue by brooks0519** [ppogg/YOLOv5-Lite#106]
when I train my dataset using efficientnet_lite0 as backbone, The following error was reported:
                 from  n    params  module                                  arguments
  0                -1  1       464  models.common.stem                      [3, 16]
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 96, in train
    model = Model(opt.cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/workspace/YOLOv5-Lite/models/yolo.py", line 85, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/workspace/YOLOv5-Lite/models/yolo.py", line 331, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
TypeError: __init__() takes 5 positional arguments but 6 were given
Need your help! tks

**Comment by ppogg** [comment]
It is possible that the code is lagging after updating too many versions.
In fact, there are too many models reproduced in this repository. We are considering deleting some of them, or updating them with the participation of participants in the community. Are you willing to submit pr?

**Comment by brooks0519** [comment]
I will have a try to debug the code of build the backbone
