### ISSUE TITLE
predictions not coming for custom dataset with quantized yolov5-lite model

### ISSUE THREAD

**Issue by shivadvg19** [ppogg/YOLOv5-Lite#107]
Hi,
trained a yolov5lite model for our custom data set and converted the .bin model into int8 format. but not able to get predictions. please help if any changes need to made for custom data set trained model deployment with Android.

**Comment by ppogg** [comment]
Hi, friend~
![image](https://user-images.githubusercontent.com/82716366/151836427-778eaafa-cdca-40a8-a160-dc73b23dab03.png)
The red line is the output node, which is connected to permute, the blue is the resize operation, make sure they are consistent.

**Comment by shivadvg19** [comment]
Thank you for your suggestion. I did the changes in yolov5.cpp and got
results.

Best Regards,
Shivakumar
