### ISSUE TITLE
How to export the model for coral edgetpu?

### ISSUE THREAD

**Issue by tyouritsugun** [ppogg/YOLOv5-Lite#114]
Hi

Thank you for your great work!

I am trying to run the model with Coral USB Accelerator connected with RaspberryPi, does anyone know how to export the models to tflite format?
https://coral.ai/

Will this one work?
https://github.com/ultralytics/yolov5

thanks
Tyou

**Comment by ppogg** [comment]
![image](https://user-images.githubusercontent.com/82716366/152711844-57d8640a-96ab-45a7-ae11-20b2bfef14bb.png)
see them~
