### ISSUE TITLE
rep_convert.py后进行detect.py报错

### ISSUE THREAD

**Issue by Bigtuo** [ppogg/YOLOv5-Lite#116]
Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 34, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\yi\Desktop\YOLOv5-Lite-new\models\experimental.py", line 119, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "D:\Anaconda\envs\eagermot\lib\site-packages\torch\nn\modules\module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'get'

**Comment by Bigtuo** [comment]
已解决，重新构建一个字典
def attempt_load(weights, map_location=None):
    # Loads an ensemble of models weights=[a,b,c] or a single model weights=[a] or weights=a
    model = Ensemble()
    D = {}  # 修改1
    for w in weights if isinstance(weights, list) else [weights]:
        attempt_download(w)
        ckpt = torch.load(w, map_location=map_location)  # load
        D['model'] = ckpt  # 修改2
        #model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
        model.append(D['model'].float().fuse().eval())  # FP32 model  # 修改3

**Comment by Bigtuo** [comment]
刚才那个地方改动，只有运行detect.py时候才能用，转换rpp_convert.py还是需要你原来的代码。顺序是先用你原代码转换，如果想要使用转换后的权重运行detect.py，再去experiment.py中进行小的修改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 晚上10:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ppogg/YOLOv5-Lite] rep_convert.py后进行detect.py报错 (Issue #116)




 
非常感谢您的反馈，您是否可以提供一个pr呢？顺便把您加入贡献者
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bigtuo** [comment]
抱歉，刚才试了你的版本代码，是无错误可以运行的。刚才错误发生原因是我将你的转换这部分代码放到我的中代码才出现那样的错误，可能是有些地方没有完全对应起来。

**Comment by ppogg** [comment]
![image](https://user-images.githubusercontent.com/82716366/153104666-ff0df832-7f65-4933-937e-d96305666941.png)
未防止他人踩坑，此处截图留用，感谢您的反馈！
