### ISSUE TITLE
Attention imporved yolov5 performance

### ISSUE THREAD

**Issue by 315386775** [ppogg/YOLOv5-Lite#117]
hi. i am interested in this project. maybe i can contribute for this good job.

| Model      | map0.5:0.95     | map0.5:0.05     | Speed CPU b1     | Speed 2080ti b1    | Speed 2080ti b32      |params(M)     | FLOPS     |
| ---------- | :-----------:  | :-----------: | :-----------:  | :-----------: | :-----------: | :-----------:  | :-----------: |
| 5s offical     | 37.2     | 56.0     | 98     | 6.4(V100)       | 0.9(V100)     | 7.2     | 16.5     |
| 5s    | 37.2     | 56.8     | 47.7     | 7.3     | 1.0     | 7.2     | 16.5     |
| 5sbackbone + C3GC     | 37.7     | 57.3     | 63.6     | 8.4     | 1.4     | 7.5     | 16.8     |
| 5sC3GC + FPN_conv     | 40.5     | 59.6     | 92.7.0     | 12.0     | 1.5     | 11.0     | 22.7     |
| 5m     | 45.2     | 63.9     | 224     | 8.2(V100)      | 1.7(V100)      | 21.2     | 49.0     |

**Comment by ppogg** [comment]
It is a real honor to catch your attention！Practically, I also noticed your experiment on yolov5 and looking forward to your pr. cheers~

**Comment by yustaub** [comment]
Hello, sir. Could you share how to implement the FPN_Conv block and the model config file? Thank you! @315386775

**Comment by 315386775** [comment]
ok. i will pr the code and model soon. thanks.

**Comment by ppogg** [comment]
您好，十分感谢您无私的pr，我已将您的代码更新到仓库中，但运行test.py出现此情况：
![image](https://user-images.githubusercontent.com/82716366/155888891-b9052a5a-37d4-4e4b-9fee-7de1e5c02beb.png)
运行train.py出现此类情况:
![image](https://user-images.githubusercontent.com/82716366/155888914-5cf19a83-2256-43e5-a5cf-1a1533a016c2.png)
初步排查应该是您使用的部分代码未pr过来而导致，例如使用YOLOv5-6.0版本进行的复现，但是yolo.py和本仓库代码存在一些出入，恳请您一起review下代码，期待您的回复，感谢！

**Comment by 315386775** [comment]
@ppogg i check the detect code. in the original yolov5 in yolo.py get.

y: torch.Size([1, 3, 80, 80, 85])
grid: torch.Size([1, 3, 80, 80, 2])
anchor_grid: torch.Size([1, 3, 80, 80, 2])

but in yolov5-lite's yolo.py get. (line with 53)

y: torch.Size([1, 3, 80, 80, 85])
grid: torch.Size([1, 1, 80, 80, 2])
anchor_grid: torch.Size([1, 3, 84, 44, 2])

The difference is _make_grid function.  Now we can locate the bug in anchor grid generator. Can you check this function, thanks.

**Comment by ppogg** [comment]
收到，我会在近期解决这个问题

**Comment by 315386775** [comment]
@ppogg Can you add my wechat to have a good communication? id: wei315386775
