### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by Fly-Pluche** [ppogg/YOLOv5-Lite#119]
README中的How to deploy链接失效

**Comment by ppogg** [comment]
抱歉，这么晚才回复你，最近被毕业论文的事忙得焦头烂额，以下关于deploy到trt的一些情况，事实上，这个repvgg的算子借鉴了这个库：https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5，你可以尝试一下，但是原先的部署脚本已经绑在了前公司的业务中，后来删除了链接，现在暂时无法开源，请见谅~

**Comment by Fly-Pluche** [comment]
没事，已经转化成功了。谢谢回复！
