### ISSUE TITLE
how to export (.torchscript .onnx) the trained YOLOv5-LITE model for the mobile compatible devices

### ISSUE THREAD

**Issue by apanand14** [ppogg/YOLOv5-Lite#122]
Hello @ppogg 

I have trained YOLOv5-lite on my custom dataset and would like to deploy (or run inference ) on android app. Can you tell me how can I export the .pt for mobile compatible devices??

Thank you for the answer in advance!!

**Comment by ppogg** [comment]
tflite? ncnn? or other inference device?

**Comment by ppogg** [comment]
like this?
https://blog.csdn.net/weixin_45829462/article/details/119787840

**Comment by apanand14** [comment]
hello, thank you for the response but I was able to convert model into .onnx and also simplified it.

**Comment by flyskywhy** [comment]
Fix it in https://github.com/flyskywhy/YOLOv5-Lite/commit/c793b44a84ffa154920e5b8d8004b3d7555e428e
