### ISSUE TITLE
Error while running detect.py

### ISSUE THREAD

**Issue by Guttappa1238** [ppogg/YOLOv5-Lite#131]
Hi, 
i'm getting this error while running `detect.py` like this

`python3 detect.py --weights v5lite-s.pt  --source 0 --conf-thres 0.25 --view-img --img-size 640`

error i got is

`AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor' terminate called without an active exception `

**Comment by ppogg** [comment]
请根据requirements.txt的环境进行配置，这个问题应该是由环境造成

**Comment by Waawww** [comment]
可以通过修改experimental.py来处理兼容性：
`    # Compatibility updates
    for m in model.modules():
        t = type(m)
        if t in [nn.Hardswish, nn.LeakyReLU, nn.ReLU, nn.ReLU6, nn.SiLU]:
            m.inplace = True  # pytorch 1.7.0 compatibility
        elif t is nn.Upsample:
            m.recompute_scale_factor = None  # torch 1.11.0 compatibility
        elif t is Conv:
            m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
`
