### ISSUE TITLE
训练一个模型，用官方APP例子部署到移动端，发现位置不对

### ISSUE THREAD

**Issue by ouxiand** [ppogg/YOLOv5-Lite#133]
发现同一张图片（车牌做了打码处理）用官方APP例子部署到移动端，发现位置不对！
云端检测得分
![image](https://user-images.githubusercontent.com/95113887/158523946-2839c5cc-99cb-47a2-8066-19162604e683.png)

NCNN检测得分
![image](https://user-images.githubusercontent.com/95113887/158523964-72d71970-57a1-46e2-81ce-f92756d17b9d.png)

**Comment by ouxiand** [comment]
请问如何处理？

**Comment by ppogg** [comment]
结果差的太多了，你可以把你的param贴到这里，我看看
