### ISSUE TITLE
v5Lite-g模型训练时map很低。

### ISSUE THREAD

**Issue by Materx** [ppogg/YOLOv5-Lite#134]
我正在进行该项目思路相同的工作，我认为将repvgg嵌入到yolov5中是一种很好的想法，根据v5Lite-g.yaml提供的模型结构，我使用nn.model重新构建了该结构，并将提供的权重转换到我重构的模型结构内，在我的测试中两个模型具有完全相同的检测结果，姑且我认为以上的工作，我是正确的。
但是当使用我自己重构的结构来训练模型时，我发现得到的map(Terminal截图)会比该项目使用lite-g训练的map(日志截图)会低很多，即使我使用了完全相同的训练配置。
![image](https://user-images.githubusercontent.com/48338930/158770197-d922ab63-e809-4b8f-8fe8-2d71f10cfa8f.png)
![image](https://user-images.githubusercontent.com/48338930/158770352-cd3d2ad7-a190-4f3e-85d1-e1847e0e736c.png)
Yolov5-Lite项目基于v5 5.0版本开发，请问，相较u版的代码，该项目是否在lite-g模型测试时添加了其他额外的操作，或者额外的方法呢？

**Comment by ppogg** [comment]
①您好，不太理解您说的具有相同的检测结果是什么意思？
②您是基于第6版做的复现？目前已经实验过，基于第六版复现，或者基于v5n复现，效果没有第五版v5s好。
③可否贴一下训练后的模型，我可以帮你review一下

**Comment by Materx** [comment]
> ①您好，您理解说的复检测结果是什么意思？ ②您是根据第 6 版复现的情况？当前实验过的，根据第 6 版，或者根据 v5n 现在，效果③可 贴一下训练后的模型，否我可以帮忙复习一下

谢谢您的回复，不好意思，之前可能没说清楚。
1. 基于您提供的预训练权重litev5-g的权重和模型的yaml文件，我使用torch在.py文件中编写了一个新的yolo模型，这个模型与litev5-g具有完全相同的层结构和权重维度，我讲预训练权重内的所有参数都复制到了我自己编写的模型中，对两个模型输入同一张照片，得到了完全相同的检测结果，连目标框的conf都完全相同，所以我认定我的模型至少在结构上应该是没有问题的。
![out](https://user-images.githubusercontent.com/48338930/159104980-42f06e7a-f98f-49b3-96a4-0f547b408254.jpg)
![out2](https://user-images.githubusercontent.com/48338930/159104982-a0111914-1b7d-4921-abec-3e7c5e316c27.jpg)
2. 我目前的代码是基于第6版的，我将第6版的代码进行了解耦重构，但保证除开模型定义以外的其他方法都与第六版完全相同，基于这套代码，我自己定义的m大小的模型比u版搞了0.02的map，但是只要切换成litev5-g的模型，效果就特别差，所以我觉得是不是除了模型外，有什么步骤我给遗漏了。 目前我有注意到的不同就是，lr您这边是0.001，lrf是0.2，u版是0.01，lrf是0.1，都是sgd优化器，nbs都是64，但您这边batch是32，u版是16.
3. 因为模型的定义方法和u版yolo的不一样，所以我贴模型出来你也load不了。下面我把模型定义的一部分贴出来，其中Detect layer因为我发现与6版的定义方式不一样，就直接copy的yolov5-lite项目中的定义方式。
以下为__init__()部分代码
```
        # ch=3, c1, c2, c3, c4, c5 = 32, 64, 128, 256, 512
        self.focus = Focus(ch, c1, 3)
        #team1
        self.conv1 = RepVGGBlock(c1, c2, 3, 2)
        self.csp1 = C3(c2, c2, n=n)
        #team2
        self.conv2 = RepVGGBlock(c2, c3, 3, 2)
        self.csp2 = C3(c3, c3, n=3*n)
        #team3
        self.conv3 = RepVGGBlock(c3, c4, 3, 2)
        self.csp3 = C3(c4, c4, n=3*n)
        #team4
        self.conv4 = RepVGGBlock(c4, c5, 3, 2)
        self.sppf = SPP(c5, c5, [5,9,13])
        self.csp4 = C3(c5, c5, n=n,shortcut=False)

        # PANet
        self.conv5 = Conv(c5, c3)
        self.up1 = nn.Upsample(scale_factor=2)
        self.csp5 = C3(c4+c3, c3, n=3*n, shortcut=False)

        self.conv6 = Conv(c3, c3)
        self.up2 = nn.Upsample(scale_factor=2)
        self.csp6 = C3(c3+c3, c3, n=3*n, shortcut=False)

        self.conv7 = Conv(c3, c3, 3, 2)
        self.csp7 = C3(c3+c3, c3, n=3*n, shortcut=False)

        self.conv8 = Conv(c3, c3, 3, 2)
        self.csp8 = C3(c3+c3, c3, n=3*n, shortcut=False)
     
        # Detect
        s = 640 
        self.detect = Detect(self.num_cls, anchors,ch=[c3, c3, c3])
        self.detect.inplace = self.inplace
        self.detect.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
        self.detect.anchors /= self.detect.stride.view(-1, 1, 1)
        self.stride = self.detect.stride
```
以下为BackBone部分代码
```
        x = self.focus(x)
        x = self.conv1(x)
        x = self.csp1(x)
        x = self.conv2(x)  # P3
        x_p3 = self.csp2(x)
        x = self.conv3(x_p3)  # P4
        x_p4 = self.csp3(x)
        x = self.conv4(x_p4)  # P5
        x = self.sppf(x)
        x = self.csp4(x)
        return x_p3, x_p4, x, x
```
以下为PAnet部分代码
```
        h_p5 = self.conv5(feas)  # head P5
        x = self.up1(h_p5)
        x_concat = torch.cat([x, p4], dim=1)
        x = self.csp5(x_concat)

        h_p4 = self.conv6(x)  # head P4
        x = self.up2(h_p4)
        x_concat = torch.cat([x, p3], dim=1)
        x_small = self.csp6(x_concat)

        x = self.conv7(x_small)
        x_concat = torch.cat([x, h_p4], dim=1)
        x_medium = self.csp7(x_concat)

        x = self.conv8(x_medium)
        x_concat = torch.cat([x, h_p5], dim=1)
        x_large = self.csp8(x_concat)
        return x_small, x_medium, x_large
```
以下为forward部分代码
```
        p3, p4, p5, feas = self._build_backbone(x)
        xs, xm, xl = self._build_head(p3, p4, p5, feas)
        x = self.detect([xs, xm, xl])
        return x
```

**Comment by ppogg** [comment]
您的工作特别的棒，我认为您的构建方式没有任何问题，但我看不到您的代码，无法确定是否是由您代码引发的问题还是v5版本问题，需要进一步推敲。
另外我需要反馈一些情况给您，之前已在v5的第六个版本进行过所有模型的迁移，e模型和g模型在coco的精度变差，此外，rep-v5n的复现精度比原始v5n低，希望这则信息对你有用。
最后一提，我觉得您的工作量非常的大，但做的非常有意义，期待您的开源。

**Comment by Materx** [comment]
谢谢 您的认可！
我比较好奇的是，基于第六版的e和g模型在coco上的精度表现，我希望在最近使用与您相同的训练参数尝试在coco训练一次，以明确我目前的复现结果与您的结果的具体差距，不知道方不方便提供一下？
我也已经主要到该项目有开设交流的qq群，并已经申请加入，后续如果我解决了我这边的问题，我也会尽快告知您。

**Comment by Materx** [comment]
目前已经发现了问题所在，最根本原因是u版的6.0和5.0版本的Detect和anchor计算定义方法不同
`anchors = m.anchor_grid.clone().cpu().view(-1, 2)  # 5.0 version`
`anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # 6.0 version`
而在6.0的yolo.py 中，Detect类，并没有定义anchor_grid属性，这意味着使用5.0的模型定义方式在6.0代码中训练时，会计算到错误的anchors，并导致模型无法收敛，使用6.0的Detect类覆盖5.0可以解决这个问题。

**Comment by ppogg** [comment]
期待大佬的更新
