### ISSUE TITLE
onnxruntime demo did not support dynamic infer?

### ISSUE THREAD

**Issue by cqray1990** [ppogg/YOLOv5-Lite#135]

**Comment by ppogg** [comment]
感谢您的反馈，动态推理包含两种，一种是动态尺寸输入，一种为模型动态图，您说的是哪种？

**Comment by cqray1990** [comment]
@ppogg 动态尺寸输入

**Comment by zwaoli** [comment]
> 感谢您的反馈，动态推理包含两种，一种是动态尺寸输入，一种为模型动态图，您说的是哪种？希望您提供更详细的信息，谢谢

请问这块export.pyl里直接使用dynamic参数导出的动态尺寸输入onnx模型可以直接推理时报tensor不匹配的问题，这块有demo示例吗

**Comment by ppogg** [comment]
目前没有，动态输入涉及的更改项较多，当时在提供demo的时候，一方面是精力有限，一方面是为了以后维护相对简单些

**Comment by qing-shang** [comment]
> 目前没有，动态输入涉及的更改项较多，当时在提供demo的时候，一方面是精力有限，一方面是为了以后维护相对简单些

我看torch detect.py是动态输入，onnx转换完 在填充图片中 预测框不准确如何才能动态输入w,h
