### ISSUE TITLE
how to export onnx as yolov5s in official web? 

### ISSUE THREAD

**Issue by cqray1990** [ppogg/YOLOv5-Lite#136]
i saw your onnxruntime code do the process as follows:

  h, w = int(self.input_shape[0] / self.stride[i]), int(self.input_shape[1] / self.stride[i])
            length = int(self.na * h * w)
            if self.grid[i].shape[2:4] != (h, w):
                self.grid[i] = self._make_grid(w, h)

            outs[row_ind:row_ind + length, 0:2] = (outs[row_ind:row_ind + length, 0:2] * 2. - 0.5 + np.tile(
                self.grid[i], (self.na, 1))) * int(self.stride[i])
            outs[row_ind:row_ind + length, 2:4] = (outs[row_ind:row_ind + length, 2:4] * 2) ** 2 * np.repeat(
                self.anchor_grid[i], h * w, axis=0)
            row_ind += length

but yolov5 did not do this

so i set export param like this:

    parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='image size')  # height, width
    parser.add_argument('--concat', type=str, default=False, help='concat or not')
    parser.add_argument('--batch-size', type=int, default=1, help='batch size')
    parser.add_argument('--dynamic', action='store_true', default=False,help='dynamic ONNX axes')
    parser.add_argument('--grid', action='store_true',default=True, help='export Detect() layer grid')
    parser.add_argument('--device', default='cpu', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')

eport can success but when load onnx model errors comes:
  sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /YOLOv5-Lite/runs/train/exp3/weights/best.onnx failed:Node (Mul_816) Op (Mul) [ShapeInferenceError] Incompatible dimensions

it did not support concat=false,grid=True params sets, onnx can  export,but detect was wrong

**Comment by ppogg** [comment]
这是详细的教程:
https://zhuanlan.zhihu.com/p/476533259
如果您想解决这个问题，请将--concat True
