### ISSUE TITLE
command issue for YOLOv5-Lite Pytorch => ONNX => TensorRT 

### ISSUE THREAD

**Issue by wangshuangbin** [ppogg/YOLOv5-Lite#138]
![2022-03-23 16-53-11屏幕截图](https://user-images.githubusercontent.com/53439625/159661659-d25cad4a-6dd5-4354-87a3-6584fdc0dd0c.png)

this command is not correct to run export.py , please help check it, thank you!

**Comment by ppogg** [comment]
好的，请尝试使用如下命令：
`python export.py --weights weights/v5lite-g.pt --batch-size 1 --img-size 640 --concat`
替换上图中第一条命令。
