### ISSUE TITLE
树莓派4B无法达到描述的benchmark

### ISSUE THREAD

**Issue by Rover-Geek** [ppogg/YOLOv5-Lite#14]
我想问下大佬的树莓派为什么这么快，我的测了很多遍，但几乎每个模型都比你多了两三倍的耗时

**Comment by ppogg** [comment]
我的硬件和软件配置:
树莓派4B
64位系统
定频1.5GHz
我感觉你的问题可能还是和系统有关,其他朋友也遇到过这种问题,系统是大头,一定要64位,用的是这个:[http://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/](http://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/)
