### ISSUE TITLE
how  to recurrence repvgg model?

### ISSUE THREAD

**Issue by chen15979695756** [ppogg/YOLOv5-Lite#140]
ppogg你好，我想复现下模型yolov5_repvgg_prune.yaml，但是没有预训练权重，看您hub中只有lite系列权重文件。是还没有上传嘛？其他预训练权重也是一样的?

**Comment by ppogg** [comment]
年代久远，此仓库仅保留了lite的四个模型，之前的模型随着服务器的更换已经找不到了，抱歉

**Comment by diangu001** [comment]
ppogg你好，我想请问一下v5lite-g是通过加载哪个权重训练出来的？如果我想对Yolov5m进行重参化，建议我加载哪个预训练权重呢？

**Comment by ppogg** [comment]
用m模型

> ppogg你好，我想请问一下v5lite-g是通过加载哪个权重训练出来的？如果我想对Yolov5m进行重参化，建议我加载哪个预训练权重呢？

可以试下m模型

**Comment by diangu001** [comment]
yolov5m.pt吗？

**Comment by ppogg** [comment]
是的
