### ISSUE TITLE
yolov5-efficient-lite0.yaml can't  load

### ISSUE THREAD

**Issue by s2pr** [ppogg/YOLOv5-Lite#144]
所有的MBConvBlock模块中定义的[ in, out, k, s ] 无法加载；
error: __init__() takes 5 positional arguments but 6 were given;

    [ -1, 1, MBConvBlock, [ 16, 32, 3, 1 ] ], # 1-P3/8
    [ -1, 3, MBConvBlock, [ 16, 24, 3, 2 ] ], # 2
    [ -1, 1, MBConvBlock, [ 24, 40, 3, 2 ] ], # 3-P4/16
    [ -1, 7, MBConvBlock, [ 40, 80, 3, 2 ] ], # 4
    [ -1, 1, MBConvBlock, [ 80, 112, 3, 1 ] ], # 5-P5/32
    [ -1, 3, MBConvBlock, [ 112, 192, 3, 2 ] ], # 6
    [ -1, 3, MBConvBlock, [ 192, 320, 3, 1 ] ], # 7

**Comment by s2pr** [comment]
yolo.py中，334行 m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
加载MBConvBlock模块时，args的参数个数变为为6，实际只需5；
请问作者这个问题是直接修改模型的yaml文件，还是修改yolo的加载；

**Comment by ppogg** [comment]
您好，common.py、yolo.py均有修改，后期仓库做过多次迭代更新，但主要是针对有v5lite的四个模型，不排除对hub中模型的代码负优化的情况，如果您也在做hub中模型的实验，欢迎您的pr
