### ISSUE TITLE
how to finetune trained model on custom dataset

### ISSUE THREAD

**Issue by apanand14** [ppogg/YOLOv5-Lite#145]
Hello,

Thank you for your work. I'm using yolov5-lite for my custom data set and would like to fine tune trained model with new data (same categories) without training from scratch. Most importantly, existing model should not forget what it has learned from the old data after fine tuning. Can you please let me how can I train? Thank you for your response.

**Comment by ppogg** [comment]
Hi, friends~ The warehouse is a secondary change to YOLOv5. For data problems, you can refer to this:
https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

**Comment by apanand14** [comment]
Helo @ppogg, I do not have any proble mwith data. i have already trained model using v5-lite but I would like to retrain (fine tune) model with new images. Can you help me how should I do it for v5-lite? thank you in advance for your answer.
