### ISSUE TITLE
我的模型是yolov5转好的ncnn在官方demo可以预测，我按照那个方法去改在这个demo里面改好不预测

### ISSUE THREAD

**Issue by pursuehdf** [ppogg/YOLOv5-Lite#146]
[文件.zip](https://github.com/ppogg/YOLOv5-Lite/files/8448750/default.zip)
模型还有cpp文件在压缩包里面

**Comment by ppogg** [comment]
已收到

**Comment by ppogg** [comment]
看了你的模型，你使用的是YOLOv5 6.0的yolov5s模型，建议还是用ncnn那一套，v5lite仓库中的Android Demo为了兼容v5lite的四个模型，基于ncnn android demo源码做过代码的改动，如果你还想使用需要改下cpp源码
