### ISSUE TITLE
How will it be cited in the paper？

### ISSUE THREAD

**Issue by hjfdsssdg** [ppogg/YOLOv5-Lite#149]
Hello, I will use the work of CONV block after REP in my paper. Could you please provide me with the specific reference format

**Comment by ppogg** [comment]
Here you are~
![image](https://user-images.githubusercontent.com/82716366/165891813-39c66c1a-32c4-42a1-a495-8979f0b5a18e.png)

**Comment by hjfdsssdg** [comment]
> Here you are~ ![image](https://user-images.githubusercontent.com/82716366/165891813-39c66c1a-32c4-42a1-a495-8979f0b5a18e.png)
Thanks
