### ISSUE TITLE
模型shuffle_block中没有bn层，程序报错

### ISSUE THREAD

**Issue by zhangdengp** [ppogg/YOLOv5-Lite#150]
将模型保存为torch=1.3版本后，运行报错：AttributeError: 'ReLU' object has no attribute 'in_channels'
发现是在yolo.py中处理shuffle_block两个分支时出现，通过打印发现shuffle_block的分支中没有bn层，导致报错，这是为什么呢？
![image](https://user-images.githubusercontent.com/44012634/164982963-eb088991-ced6-4cce-b30f-2cea889bde52.png)

**Comment by ppogg** [comment]
请试着按照requirement.txt进行环境配置，另外此前未发现这种情况，你是更改了代码吗？
