### ISSUE TITLE
YOLOv5-Lite单通道图像训练推理

### ISSUE THREAD

**Issue by ForBetterDl** [ppogg/YOLOv5-Lite#153]
如题，如果是对单通道(灰度)图像进行训练推理，代码中需要进行哪些修改以适配此操作呢。

**Comment by ppogg** [comment]
不需要更改的，直接训即可

**Comment by freedom1979** [comment]
会提高推理速度吗？

**Comment by ppogg** [comment]
不会的

**Comment by freedom1979** [comment]
虽然单通道的图像数据变少了，但是网络还是有那么多参数来运算。不知是否这么理解。
那我可以修改网络结构，以减少网络参数，来提高灰度图像的识别速度吗？
