### ISSUE TITLE
有没有测试过加载shufflenet预训练权重和没有预训练权重的区别？

### ISSUE THREAD

**Issue by Summ41** [ppogg/YOLOv5-Lite#16]

**Comment by ppogg** [comment]
没试过此类的对比,或许你可以做下这些实验

**Comment by ppogg** [comment]
这里补充一个有无预训练权重的对比(不完全正确,但可以当作参考):[https://github.com/ppogg/shufflev2-yolov5/issues/8](https://github.com/ppogg/shufflev2-yolov5/issues/8)
无预训练权重迭代时间更长,且更容易陷入局部鞍点
