### ISSUE TITLE
Yolov5-lite pytorch

### ISSUE THREAD

**Issue by Aoi-00** [ppogg/YOLOv5-Lite#160]
Is there a way to load yolov5 lite like how we load the original yolov5 without downloading like so:

import torch
from PIL import ImageGrab

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Image
im = ImageGrab.grab()  # take a screenshot

# Inference
results = model(im)

Is there a way to do this with yolov5-lite-s without downloading the entire github? I want to use this for my rpi project to see if I can do image recognition without forwarding it to a PC.

**Comment by ppogg** [comment]
Thanks for your suggestions, but I'm the only one maintaining the repository at the moment, and I need work and can't put much effort into it
