### ISSUE TITLE
v5Lite-e

### ISSUE THREAD

**Issue by HuKai97** [ppogg/YOLOv5-Lite#162]
请问为什么v5Lite-e中的head用的是DWConv替换C3呢，而不继续像backbone那样用Shuffle_Block替换呢？

![~{K6~(OLPYOPNDLJ1RYKWM9](https://user-images.githubusercontent.com/68494594/169026699-6bc34990-57f3-4bfd-8e8b-57fccc70be33.png)

**Comment by ppogg** [comment]
你可以做下实验，我个人认为head部分不需要太重，比较提取特征的大部分工作在骨干进行
