### ISSUE TITLE
mean_vals和norm_vals

### ISSUE THREAD

**Issue by chen990627** [ppogg/YOLOv5-Lite#163]
请问大佬mean和norm怎么获得呀

**Comment by chen990627** [comment]
> 请问大佬mean和norm怎么获得呀

![image](https://user-images.githubusercontent.com/48650961/169244835-781824c8-f692-4b58-9c24-245b723f4e7a.png)
还有就是我看这一段没有别的地方引用，是不是没有用处哇

**Comment by chen990627** [comment]
> 请问大佬mean和norm怎么获得呀

yolov5.register_custom_layer("YoloV5Focus", YoloV5Focus_layer_creator);
    yolov5.opt.num_threads = ncnn::get_big_cpu_count();
    yolov5.opt.blob_allocator = &blob_pool_allocator;
    yolov5.opt.workspace_allocator = &workspace_pool_allocator;

    char parampath[256];
    char modelpath[256];
    sprintf(parampath, "%s.param", modeltype);
    sprintf(modelpath, "%s.bin", modeltype);

    yolov5.load_param(parampath);
    yolov5.load_model(modelpath);

    target_size = _target_size;

    mean_vals[0] = 1 / 255.f;
    mean_vals[1] = 1 / 255.f;
    mean_vals[2] = 1 / 255.f;
    norm_vals[0] = 0;
    norm_vals[1] = 0;
    norm_vals[2] = 0;

还有就是这一段的mean和norm我看没有别的地方引用，是不是没啥用处呀

**Comment by ppogg** [comment]
是这个，默认使用ncnn的固定参数
