### ISSUE TITLE
按照mnn_demo内文档运行yolov5lite_s模型时输出图像有问题

### ISSUE THREAD

**Issue by apuapu347** [ppogg/YOLOv5-Lite#166]
模型：yolov5lite-s.mnn
cmake版本：3.10.2
protobuf版本：3.19.1
mnn版本：1.2.0
opencv：3.4.6
按照mnn_demo里的文档进行编译 直接cmake mnn_demo里的cmakelist 报错为main.cpp找不到MNN/MNNDEFINE.h等头文件
添加了如下内容
include_directories(${PROJECT_SOURCE_DIR})
然后重新运行 
cmake编译得到可执行文件yolov5
然后从你提供的链接得到v5lite-s.mnn模型
执行yolov5后 终端显示如下
The forward time is: 449.618ms
但是后续得到的结果图片显示的框有问题
![output](https://user-images.githubusercontent.com/105356362/170819063-23721065-5919-4197-975b-ca70ca6e90b2.jpg)
图片的格式也有问题
麻烦看看问题可能出在哪里 多谢

模型来自这个链接https://drive.google.com/drive/folders/1mSU8g94c77KKsHC-07p5V3tJOZYPQ-g6

**Comment by ppogg** [comment]
你是否已经在你的电脑上安装编译好mnn？
推理脚本的均值方差均已修改好，应该是环境的问题
如果已经安装好，按照下面的流程进行编译：
![image](https://user-images.githubusercontent.com/82716366/172291427-7d7431d3-323c-4897-879a-66b451b3d395.png)

**Comment by apuapu347** [comment]
确实是按照这个流程实现的 mnn也都编译了 相应的库也都得到了 编译过程也没出现问题 此外 这mnn_demo里的cmakelist我修改了一下 添加了一个库文件夹
但是运行完毕后得到的图像总有问题 
想请问一下 我用的最新版本的mnn编译 会是这个问题吗 

![image](https://user-images.githubusercontent.com/105356362/172307256-18a60cac-3bc1-4bb6-8991-b4ed43ffb003.png)

![image](https://user-images.githubusercontent.com/105356362/172307489-fa65e58d-26da-4efa-bb12-bb1d330ca14c.png)

**Comment by ppogg** [comment]
最好版本要对齐，我是用的去年10月份的mnn版本

**Comment by cc19860606** [comment]
请问下include_directories(${PROJECT_SOURCE_DIR})是加在CMakeLists.txt里么？ @apuapu347 
我也找不到MNN/MNNDEFINE.h等头文件

**Comment by cc19860606** [comment]
请问下include_directories(${PROJECT_SOURCE_DIR})是加在CMakeLists.txt里么？ @apuapu347 
我也找不到MNN/MNNDEFINE.h等头文件 ，方便介绍下怎么解决这个问题么？

**Comment by cc19860606** [comment]
我也找不到MNN/MNNDEFINE.h等头文件， 能问下include_directories(${PROJECT_SOURCE_DIR}) 加在哪么？能具体讲下怎么解决的么？
@apuapu347

**Comment by apuapu347** [comment]
是的啊 Cmakelist里面原本就有吧 头文件是需要在MNN里面编译得到的  具体的看MNN文档 没编译的话就没有哦

**Comment by ppogg** [comment]
已更新1.5版本，提供新的MNN demo，有问题可加群问
