### ISSUE TITLE
gpu使用到时nnapi么？

### ISSUE THREAD

**Issue by kingmacth** [ppogg/YOLOv5-Lite#170]
无安装了APP感觉CPU和GPU到速度没啥变化呢。还没编译暂时还没发监控CPU使用量有没有变化

**Comment by ppogg** [comment]
其实在手机上，如果使用的是ncnn，cpu要比gpu好

**Comment by ppogg** [comment]
这个和底层优化以及模型有关，在移动端你会发现小模型直接加载到cpu跑会更快
