### ISSUE TITLE
export支持转tfjs么，

### ISSUE THREAD

**Issue by lijianyu1985** [ppogg/YOLOv5-Lite#171]

**Comment by lijianyu1985** [comment]
推理结果：
![image](https://user-images.githubusercontent.com/1027001/172364622-ed5c8e58-bc7a-4840-8ce3-6aff402bf1f9.png)
model.json
![image](https://user-images.githubusercontent.com/1027001/172364651-68704f18-a749-468c-8dab-314b9c9393e8.png)
不知道这个推理结果该怎么用，正常不应该是一个四个元素的数组么？

**Comment by bedapudi6788** [comment]
@lijianyu1985 how did you export to tfjs?

**Comment by lijianyuhoopox** [comment]
I used two ways to export to tfjs:
1. copy the model to yolov5 and run export to export the model to tfjs model
2. just run download.sh to get the tfjs model: https://github.com/PINTO0309/PINTO_model_zoo/tree/main/180_YOLOv5-Lite
