### ISSUE TITLE
请问报错：TypeError: list indices must be integers or slices, not list的原因是什么

### ISSUE THREAD

**Issue by chengzihencai** [ppogg/YOLOv5-Lite#176]
按照大佬的思路将改进点在yolov5上实现，在将Concat改为ADD时报如题错误，请问这个错误原因及修改方法

**Comment by chengzihencai** [comment]
backbone中使用大佬的改进方法，neck使用DWConv，这两部分都能正常训练，而将后两个Concat替换为ADD后报如题错误。链接中是改动了的网络yaml文件、common.py（添加的模块在最下部）、yolo.py。
链接：https://pan.baidu.com/s/1x7Bv-wW60aA1wixVI2ksWw?pwd=1111 
提取码：1111

**Comment by zy-zy-coder** [comment]
你好，请问这个问题解决了马
