### ISSUE TITLE
分享picodet模型预训练模型

### ISSUE THREAD

**Issue by 3386307933** [ppogg/YOLOv5-Lite#177]
在coco数据集上picodet预训练模型。
链接：https://pan.baidu.com/s/1-X8IOckwD4tBizOnBt9Z8A 
提取码：pogg

**Comment by Jubbuuliiing** [comment]
这个预训练模型有用吗，使用在yolov5里面

**Comment by Cxm98** [comment]
链接失效了，大佬方便评论再分享一下吗
