### ISSUE TITLE
Rethinking YOLOv5 Lite OpenVINO Inference

### ISSUE THREAD

**Issue by 2050airobert** [ppogg/YOLOv5-Lite#178]
Hi，
      YOLOv5 Lite OpenVINO Inference ：  https://github.com/ppogg/YOLOv5-Lite/blob/master/python_demo/openvino/README.md
    请问下 这个耗时是在哪个型号的cpu上测试的？
    单核还是多核的时间呢？

BR

**Comment by ppogg** [comment]
Inter i5 4590 单核测试
