### ISSUE TITLE
自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？

### ISSUE THREAD

**Issue by 874858145** [ppogg/YOLOv5-Lite#181]
操作流程：
python train.py --data data\pallet.yaml --cfg models\v5Lites-s-pallet.yaml --weights weights\v5lite-s.pt --batch-size 1 --device cpu

![QQ图片20220706132104](https://user-images.githubusercontent.com/26745620/177474658-df4a6eab-f3ef-4053-a455-123afa316ad5.png)
pallet.yaml

![QQ图片20220706132111](https://user-images.githubusercontent.com/26745620/177474690-e8d644bd-da52-44f2-944a-9de52b8becad.png)
v5Lites-s-pallet.yaml

python export.py --weights weights\v5lite-s-pallet.pt --img-size 640 
python -m onnxsim weights\v5lite-s-pallet.onnx weights\v5lite-ss-pallet.onnx 
onnx2ncnn.exe v5lite-ss-pallet.onnx v5lite-ss-pallet.param v5lite-ss-pallet.bin

测试图片
![0053](https://user-images.githubusercontent.com/26745620/177475485-4cf624b4-339a-4db1-b78a-41ef36015b12.jpg)
运行detect.py的结果
![0053-r](https://user-images.githubusercontent.com/26745620/177475928-8525adc9-0dad-412f-95a7-cc7dcae53cb0.jpg)

![1657085172860](https://user-images.githubusercontent.com/26745620/177475155-d7bbe55d-9cec-4d55-b7ad-5d6a9211dff5.jpg)

权重和模型文件，百度云
[https://pan.baidu.com/s/1sUnRD3Uc-7VsrZIkY4vcVA](url)
提取码：lve8

**Comment by ppogg** [comment]
![image](https://user-images.githubusercontent.com/82716366/177593768-409ad1cf-7c97-43f7-b5d5-00e9f3d446b1.png)
请不同concat在一起，这样会导致子输出节点失效

**Comment by 874858145** [comment]
![1657179742986](https://user-images.githubusercontent.com/26745620/177719403-a850a930-cca2-4665-ac25-bdd14f5c26fb.png)

我把这两句注释掉了，转换后依旧不能识别。
我尝试用onnxruntime对群主的模型转onnx进行推理，有东西输出，而用我自己训练的模型转onnx，没有任何东西输出。也就是说起码从pytorch转onnx就开始有问题了，所以后续转ncnn也有问题。现在就是看前面几步哪出问题，种种迹象表明我自己模型本身有问题，但为什么在群主的detect.py却能识别，这是我比较迷惑的

**Comment by ppogg** [comment]
> ![1657179742986](https://user-images.githubusercontent.com/26745620/177719403-a850a930-cca2-4665-ac25-bdd14f5c26fb.png)
> 
> 我把这两句注释掉了，转换后依旧不能识别。 我尝试用onnxruntime对群主的模型转onnx进行推理，有东西输出，而用我自己训练的模型转onnx，没有任何东西输出。也就是说起码从pytorch转onnx就开始有问题了，所以后续转ncnn也有问题。现在就是看前面几步哪出问题，种种迹象表明我自己模型本身有问题，但为什么在群主的detect.py却能识别，这是我比较迷惑的

害，你用转化后的onnx，然后用我的onnxruntime脚本推理，看看有没有框，等你回复

**Comment by 874858145** [comment]
> 

试了一下。出框了，看来是我写的onnx推理有问题。也就是说是onnx转ncnn,呢个环节有问题了。

**Comment by 874858145** [comment]
搞了一圈onnx,再看ncnn,发现是自己.cpp文件的目标图像尺寸设置有问题，写成了320了，当初训模型的时候设的是640的，后来改640，就出框了。不过发现群主的模型设320和640都能正常识别。群主大大有空解答下。
终于出框了，被自己菜哭了。。。。。。
感谢群主大大不遗余力的支持

**Comment by 874858145** [comment]
搞了一圈onnx,再看ncnn,发现是自己.cpp文件的目标图像尺寸设置有问题，写成了320了，当初训模型的时候设的是640的，后来改640，就出框了。不过发现群主的模型设320和640都能正常识别。群主大大有空解答下。
终于出框了，被自己菜哭了。。。。。。
感谢群主大大不遗余力的支持

**Comment by johninn** [comment]
> 

这两句一定要注掉吗？注掉转换出来的onnx就跑不起来了，不注掉onnx是没问题的

**Comment by johninn** [comment]
我碰到同样的问题了，但是解决不了
如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果
如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错

**Comment by 874858145** [comment]
我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppogg/YOLOv5-Lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181)





 
我碰到同样的问题了，但是解决不了
 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果
 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错

**Comment by johninn** [comment]
> 我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" ***@***.***&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

640，320都试了都没用。所以export里注掉那两行是必须的嘛？

**Comment by 874858145** [comment]
我明天回去翻下代码看看，太久没弄，记不大清楚了。你是量化了吗？？我当时好像还没弄到转化为int8这一步，用的好像是f16。好多东西都记不大清了。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppogg/YOLOv5-Lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上10:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181)





  
我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" @.&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
640，320都试了都没用。所以export里注掉那两行是必须的嘛？

**Comment by 874858145** [comment]
看了下我的那个export.py，是把那两行注释掉了，估计你得看看你的ncnn程序有没有问题，我当初就是ncnn程序那里有问题，后来改了。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日 22:29:34
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181)




  
我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" @.&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
640，320都试了都没用。所以export里注掉那两行是必须的嘛？

**Comment by johninn** [comment]
有没有ncnn c++代码可以参考下？

**Comment by johninn** [comment]
> 看了下我的那个export.py，是把那两行注释掉了，估计你得看看你的ncnn程序有没有问题，我当初就是ncnn程序那里有问题，后来改了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月2日 22:29:34 收件人: ***@***.***&gt;; 抄送: "State ***@***.******@***.***&gt;; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" @.&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 640，320都试了都没用。所以export里注掉那两行是必须的嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

有没有ncnn代码可以参考下啊？

**Comment by 874858145** [comment]
群主好像有给吧，我记得当时在github上拉下来的，你找找


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月3日 11:10:00
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181)




  
看了下我的那个export.py，是把那两行注释掉了，估计你得看看你的ncnn程序有没有问题，我当初就是ncnn程序那里有问题，后来改了。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月2日 22:29:34 收件人: @.&gt;; 抄送: "State @.@.&gt;; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" @.&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 640，320都试了都没用。所以export里注掉那两行是必须的嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt;
  
有没有ncnn代码可以参考下啊？

**Comment by johninn** [comment]
> 群主好像有给吧，我记得当时在github上拉下来的，你找找
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月3日 11:10:00 收件人: ***@***.***&gt;; 抄送: "State ***@***.******@***.***&gt;; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 看了下我的那个export.py，是把那两行注释掉了，估计你得看看你的ncnn程序有没有问题，我当初就是ncnn程序那里有问题，后来改了。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月2日 22:29:34 收件人: @.&gt;; 抄送: "State @.@.&gt;; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ppogg/YOLOv5-Lite" @.&gt;; 发送时间:&nbsp;2023年2月2日(星期四) 晚上9:54 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 640，320都试了都没用。所以export里注掉那两行是必须的嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 有没有ncnn代码可以参考下啊？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

嗯我就是用的repo里的cppdemo。。

**Comment by linfeng-789** [comment]
> > 群主好像有给吧，我记得当时在github上拉下来的，你找找
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年2月3日 11:10:00 收件人: _**@**_.**_>; 抄送: "State _**@**_._**_**@**_.**_>; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 看了下我的那个export.py，是把那两行注释掉了，估计你得看看你的ncnn程序有没有问题，我当初就是ncnn程序那里有问题，后来改了。 … ---原始邮件--- 发件人: @.> 发送时间: 2023年2月2日 22:29:34 收件人: @.>; 抄送: "State @.@.>; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我之前遇到那个问题是我训练的时候是把图片处理成640x640，而我实际跑的ncnn那程序，我把图片整成320x320的，这输入到模型里面，肯定没结果，你看看你的ncnn的程序是不是也这样吧。最近都没有弄这个了 … ------------------ 原始邮件 ------------------ 发件人: "ppogg/YOLOv5-Lite" @.>; 发送时间: 2023年2月2日(星期四) 晚上9:54 @.>; @.>;"State @.>; 主题: Re: [ppogg/YOLOv5-Lite] 自己训练的模型转换ncnn，无法识别，但用作者提供的v5lite-s.pt转ncnn，能正常识别，应该从哪里开始找问题？？ (Issue #181) 我碰到同样的问题了，但是解决不了 如果不注掉export.py里那两行，ncnn的模型没有结果，onnx可以出结果 如果注掉那两行，ncnn param文件不会有concat层，但是onnx运行demo直接报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.> 640，320都试了都没用。所以export里注掉那两行是必须的嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.> 有没有ncnn代码可以参考下啊？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 嗯我就是用的repo里的cppdemo。。

请问后来解决了吗，我也是一样的问题。
