### ISSUE TITLE
Unable to run detect.py for testing

### ISSUE THREAD

**Issue by joel5638** [ppogg/YOLOv5-Lite#186]
Im testing on few images. Im unable to run 
python3 detect.py --source home/joel/img4.jpg --weights v5lite-s.pt.

Im getting this error: 
**AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'**

Tried resolving the environmental issues too Nothing is working. I have created new env and install requirements.txt. Still did not work.
I have also used --device as cpu. Still nothing works

**Comment by ppogg** [comment]
Thanks for using YOLOv5 Lite！In fact, this is caused by an overly high version of pytorch. Please follow the requirements.txt to install

**Comment by gamegrd** [comment]
Thank you for this amazing project.
Will you support the newest version of pytorch?
