### ISSUE TITLE
gpu上几乎没增速

### ISSUE THREAD

**Issue by Acolalalasia** [ppogg/YOLOv5-Lite#19]
大佬，我测试了下gpu上的推理速度，几乎没有提速，这个是正常的吗？

**Comment by ppogg** [comment]
是的,具体参见这条issue[https://github.com/ppogg/shufflev2-yolov5/issues/10](https://github.com/ppogg/shufflev2-yolov5/issues/10)
后期不定时更新,会适配repvgg,efficient-lite等网络

**Comment by ppogg** [comment]
这里更新了repvgg yolov5模型
