### ISSUE TITLE
端侧如何学习可否讲一下

### ISSUE THREAD

**Issue by UnstoppableCurry** [ppogg/YOLOv5-Lite#199]
学了半年,也只是在服务器上跑yolo 
请问能不能讲一下 在端侧的学习路线
最近搞了半年的算法部署android  都是ncnn现成代码拿来用  但是很明显感觉自己的提升很有限  仅仅只学了学android开发和jni 通信 还有c++
像您这样的大佬是如何起步端侧的呢
您的博客好多都看不懂,但是这个安卓部署的效果太强了, banckmark sota.......如何能接近您

**Comment by ppogg** [comment]
这个主要还是靠自己摸索了，很难会有人手把手教学的，大部分开自学了，加油~
