### ISSUE TITLE
大佬能提供训练的yolov4-tiny、yolov3-tiny的链接或者代码吗？

### ISSUE THREAD

**Issue by ahhhxxx** [ppogg/YOLOv5-Lite#2]

**Comment by ppogg** [comment]
我不太理解您的意思，是提供yolov3和yolov4的yaml文件吗？

**Comment by ahhhxxx** [comment]
![image](https://user-images.githubusercontent.com/57949429/130355544-836585ee-f26e-4e90-9379-dece33c49d06.png)
是的 我也想做这样的对比，大佬能提供YOLOv3-tiny,yolov4-tiny的代码吗？

**Comment by ppogg** [comment]
呀，么得问题哈哈，yolov3的指标用的是darknet官网的，yolov4的指标用的是scale-yolov4论文的，明早我把那几个链接发给你~

**Comment by ahhhxxx** [comment]
> 呀，么得问题哈哈，yolov3的指标用的是darknet官网的，yolov4的指标用的是scale-yolov4论文的，明早我把那几个链接发给你~
好的 谢谢大佬

**Comment by ppogg** [comment]
以下链接，你所需要的yolov3-tiny的iou@0.5指标：
链接：[https://pjreddie.com/darknet/yolo/](https://pjreddie.com/darknet/yolo/)
yolov3-tiny的iou@.5:0.95指标：
[https://github.com/RangiLyu/nanodet](https://github.com/RangiLyu/nanodet)
yolov4-tiny的iou@0.5和iou@.5:0.95指标：
[https://arxiv.org/abs/2011.08036](https://arxiv.org/abs/2011.08036)
