### ISSUE TITLE
是否考虑p6的模型

### ISSUE THREAD

**Issue by yongjingli** [ppogg/YOLOv5-Lite#20]
请问是否考虑加入p6的模型进行对比。 @ppogg

**Comment by ppogg** [comment]
事实上,这边的消融实验已经对比到p2-p4,你可以看下面这张图,是上周跑的benchmark:
<img src="https://user-images.githubusercontent.com/82716366/131332781-bf32716f-562d-42a8-a048-9251f71d5a29.jpg" width="400"/><br/>
红色框是p2,使用的是light-fpn(two head+depthwise+通道剪枝),黄色框是p4,使用的是light-panet(three head+C3 block+CSPnet),如果使用p6,推理时间会不低于150ms(input_size=320).
设计这个模型的初衷是为了适配芯片和端侧设备,对我而言,p6的头实在是太奢侈了,要不起~

**Comment by yongjingli** [comment]
好的，谢谢你的答复，还有另外一个问题，这里的模型好像都没有加入SPP模块，这个的性价比好像还挺高的，请问你有做这实验吗？ @ppogg

**Comment by ppogg** [comment]
spp内部太多池化分支，对于我要部署的设备来说过于高昂，但是gpu、npu和cpu是非常work的，有个借鉴repvgg重参化的yolov5模型，近期会考虑开源

**Comment by yongjingli** [comment]
哇， 挺不错的，请问你是将SPP重参数化，还是将里面所有的3x3卷积重参数化？ @ppogg

**Comment by ppogg** [comment]
是的，是将骨干中所有的3*3卷积重参化，速度不会有任何提升，但是可以涨1-2个点，后期将这涨的1-2个点填补到silu→relu的替换上，得到一个精度和yolov5s差不多，但是速度可以快5-10%的rep-yolov5s

**Comment by yongjingli** [comment]
嗯嗯，期待你的开源，如果重参数化可以应用到depthwise convolution上那就好了，可惜目前shufflenet和mobilenet这些还不能用上。

**Comment by ppogg** [comment]
是的，不过我认为在分组卷积前面多加一层1*1进行连接，可能对涨点作用不会太大

**Comment by yongjingli** [comment]
是的，多加一个1x1的支路，两个并行的1x1感觉跟一个串行的1x1感觉没什么区别，但可以试试，甚至还可以多加一个residual，说不定有奇效，哈哈。

**Comment by ppogg** [comment]
这里刚更新Tranformer-yolov5-p6的配置文件，你可以试一试效果

**Comment by yongjingli** [comment]
好的，谢谢哈 @ppogg， 可以加下你微信不，请教下。

**Comment by drilistbox** [comment]
请问两位大佬，在检测头上做重参数(而不是主干网)，能有性能的提升么
