### ISSUE TITLE
cpp_demo中的MNN使用交叉编译aarch64-linux-gnu-gcc与g++,make后显示找不到MNN/MNNDefine.h

### ISSUE THREAD

**Issue by MrSuen** [ppogg/YOLOv5-Lite#200]
![image](https://user-images.githubusercontent.com/69710217/191447555-d2556579-5bf6-4d26-82b3-8df64d50bd27.png)
已经将MNN编译成功了，/usr/local/include中是有MNN文件夹的，也有MNNDefine.h,都是用的交叉编译，请问该如何解决？

**Comment by cc19860606** [comment]
您好，我也碰到一样问题，请问是怎么解决的 @MrSuen

**Comment by MrSuen** [comment]
> 您好，我也碰到一样问题，请问是怎么解决的 @MrSuen mnn_demo这个文件夹建在哪个目录下啊
已经解决，mnn的cpp_demo可以复制到任意位置，我是在/home/用户名/下，我编译MNN时，在sudo make install后，将头文件编译在了系统目录/usr/local/include/MNN下，我的做法是将MNN文件夹拷贝到yolov5-lite/cpp_demo/mnn/include/下，同目录的Yolo.h中的#include <MNN/MNNDefine.h>改为"MNN/MNNDefine.h"，以此类推做修改

**Comment by cc19860606** [comment]
您好:
我将MNN编译后的include下的MNN文件夹拷贝到mnn/include/，也将Yolo.h中相关的头文件从<&gt;改成了“”，编译结果如下：
[ 75%] Building CXX object CMakeFiles/yolov5.dir/src/util.cpp.o
[100%] Linking CXX executable ../yolov5
/usr/bin/ld: cannot find -lMNN
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/yolov5.dir/build.make:171: ../yolov5] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/yolov5.dir/all] Error 2

不知道您碰见过这个问题么？您拷贝MNN文件夹是整个MNN还是工程里include下的MNN文件夹啊？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ppogg/YOLOv5-Lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ppogg/YOLOv5-Lite] cpp_demo中的MNN使用交叉编译aarch64-linux-gnu-gcc与g++,make后显示找不到MNN/MNNDefine.h (Issue #200)





  
您好，我也碰到一样问题，请问是怎么解决的 @MrSuen mnn_demo这个文件夹建在哪个目录下啊
 已经解决，mnn的cpp_demo可以复制到任意位置，我是在/home/用户名/下，我编译MNN时，在sudo make install后，将头文件编译在了系统目录/usr/local/include/MNN下，我的做法是将MNN文件夹拷贝到yolov5-lite/cpp_demo/mnn/include/下，同目录的Yolo.h中的#include <MNN/MNNDefine.h&gt;改为"MNN/MNNDefine.h"，以此类推做修改

**Comment by MrSuen** [comment]
> 

对，后续是有这个问题的，会提示cannot find -lMNN，你需要把当时MNN编译后生成的libMNN.so复制到报错提示的路径下，比如你这边显示找不到动态库的路径是/usr/bin/ld，你就复制到这下面就可以
