### ISSUE TITLE
请问有在arm端跑这个模型的吗，处理每张图片的耗时可以分享一下吗

### ISSUE THREAD

**Issue by MrSuen** [ppogg/YOLOv5-Lite#204]
我用a53跑的，1500*1938分辨率的图片，板端1700ms，虚拟机200ms，感觉有些夸张，想看看你们的数据，非常感谢

**Comment by ppogg** [comment]
这个速度，这么低端的核，其实是差不多的，宽高的分辨率是原生仓库的5倍，计算量大约是25倍
