### ISSUE TITLE
文档中我看4b可以运行10帧多？说是80ms左右，实际用cm4跑 只有2帧，问题在哪呀

### ISSUE THREAD

**Issue by jd3096-mpy** [ppogg/YOLOv5-Lite#206]
这是我的打印信息：

pi@dog:~/YOLOv5-Lite $ python detect.py --source 0 --img-size 320
/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
Namespace(weights='weights/v5lite-s.pt', source='0', img_size=320, conf_thres=0.45, iou_thres=0.5, device='', view_img=False, save_txt=False, save_conf=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False)
YOLOv5 🚀 v1.4-46-gcdf42dd torch 1.11.0 CPU

Fusing layers...
/usr/local/lib/python3.9/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /root/pytorch/aten/src/ATen/native/TensorShape.cpp:2227.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 230 layers, 1640661 parameters, 0 gradients, 3.9 GFLOPS
1/1: 0...  success (320x240 at 30.00 FPS).

0: 256x320 Done. (0.336s)
0: 256x320 Done. (0.542s)
0: 256x320 Done. (0.508s)
0: 256x320 Done. (0.561s)
0: 256x320 Done. (0.494s)
0: 256x320 Done. (0.601s)

是用的v5lite-s模型 img-size也改成了320
请问还有哪里没设置对吗，为何帧数相差如此之大

**Comment by ppogg** [comment]
搜一下历史问题，有这方面的解答

**Comment by jd3096-mpy** [comment]
> 搜一下历史问题，有这方面的解答

感谢，找到问题了，不是直接用根目录的test.py 而是要用examples下面的。。。
希望能在readme里面写一下，不然像我一样的小白肯定直接奔着，根目录下的test.py去了。。。
