### ISSUE TITLE
你好  请问训练细节和yolo5一样？只需要yaml文件改对就可以？核心后处理一样吗？

### ISSUE THREAD

**Issue by henbucuoshanghai** [ppogg/YOLOv5-Lite#21]
请问原yolo5直接common加上模块？yaml换一下就可以按照yolo5的训练进行训练？

请问后处理一样吗？模型三个头的输出维度？ 和原版yolo5一样是吗？

多谢

**Comment by ppogg** [comment]
是的,先common加上模块,接着yolo里面注册模块,yaml进行替换,即可进行训练
后处理和5.0版本的一模一样,可以无需修改,三个头的shape也是一样的,

另外,该工程为了方便大家白嫖,不敢在原版上面修改太多东西,所以你以前怎么使用yolov5 5.0版本,这个就怎么用,后续6.0版本出来,会将功能和代码移过去

**Comment by henbucuoshanghai** [comment]
热心的回复 很好的git&nbsp; 感激！！！但是另外帖子我问了&nbsp; 为何加上mobilenet&nbsp; 或shuffnet12&nbsp; &nbsp;速度为何依旧很慢？在手机上只能15fps左右&nbsp;
请问怎样改进yolo5能达到35fps左右？


手机端检测 有什么好的快的模型？

**Comment by ppogg** [comment]
好的朋友,我想问下你是外国人吗,你的问题我感觉语句不是很通顺,你可以重述下你的问题吗,用英文或者中文都是可以的
