### ISSUE TITLE
训练有问题，结果很小

### ISSUE THREAD

**Issue by FYM1209** [ppogg/YOLOv5-Lite#210]
![image](https://user-images.githubusercontent.com/93715148/201317877-67dd257b-ed04-4aa8-be83-ead18d717914.png)
这是我第一轮的结果，那个地方和官方写的不太一样，官方好像只有两个值，如果我也改成两个 就报错了

**Comment by ppogg** [comment]
你这个问题去yolov7的仓库问比较合适
