### ISSUE TITLE
ncnn测试很慢的问题

### ISSUE THREAD

**Issue by chenweifu2008** [ppogg/YOLOv5-Lite#24]
大佬请问一下，我下载了最新版的ncnn，在服务器电脑Linux 18.04系统上安装和编译也都过了没啥问题，都按照教程编译也没什么特别操作。
服务器电脑配置：CPU： Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz  GPU：TITAN RTX
就在那个编译的ncnn工程下跑了你的yolov5ss.cpp[1](https://github.com/ppogg/YOLOv5-Lite/blob/master/ncnn_demo/yolov5ss.cpp)  和你提供的ncnn模型[2](https://github.com/ppogg/YOLOv5-Lite/tree/master/ncnn_demo/model_zoo) ，
为什么测试的速度很慢，大概一两秒才能出一张结果，而且那张person的图片竟然有一个误检（一个人框里面多了一个小框我没这里办法上传图片）。
我跑pytorch模型速度(cpu)就相对正常。
请问您ncnn部署测试是怎么做的呢？是因为ncnn在电脑上跑本来就很慢吗也不太可能一两秒吧？我对ncnn部署一窍不通，请指教，谢谢

**Comment by ppogg** [comment]
嗨，朋友，我使用的ncnn版本是20210525那一版
person出现一个误检框应该是阈值卡太低，我已更改了阈值，或者你自己可以修改一下，正常是在0.45-0.65之间
接着ncnn一张图跑了快1-2s，一个可能和你的input_size有关【1】，也可能是你编译正确有关【2】
【1】640*640我在自己两台电脑和同事的电脑测过，正常检测应该是50-100ms之间（双核），320*320在树莓派4b大概是80-100ms左右一帧
【2】ncnn正确编译可能也有关系，你可以先测下其他轻量模型，看看是不是耗时也这么长

**Comment by chenweifu2008** [comment]
@ppogg 解决了,是我的ncnn编译的问题
但是我发现ncnn yolov5.cpp 图片的输入不是640*640 等正方形，而是将原图片等比例resize了，我原图是1280×960就被resize成640*480了，这样跟我们训练的时候不就不一样了吗？可是yolov5 pytorch 测试那边输入是正方形

**Comment by chenweifu2008** [comment]
> @ppogg 解决了,是我的ncnn编译的问题
> 但是我发现ncnn yolov5.cpp 他的代码 图片的输入不是640×640 等正方形，而是将原图片等比例resize了，我原图是1280×960就被resize成640_480了，这样跟我们训练的时候不就不一样了吗？可是yolov5 pytorch 测试那边输入是正方形

**Comment by ppogg** [comment]
是的，原先编译出来的ncnn是会默认做letter box的，不过YOLOv5-Lite这个模型在x86上可能也不会太快呢

**Comment by NTHoang99** [comment]
@ppogg where can i find ncnn 20210525 version to download ? I try using ncnn 20210720 on x86 but when running the application immediately it crashes ?

**Comment by ppogg** [comment]
> @ppogg在哪里可以找到 ncnn 20210525 版本下载？我尝试在 x86 上使用 ncnn 20210720 但是当立即运行应用程序时它崩溃了？

[https://github.com/Tencent/ncnn/releases](https://github.com/Tencent/ncnn/releases)

here~

**Comment by NTHoang99** [comment]
@ppogg it ran :v. tks so much, i think you should require everyone using exactly version of ncnn in Readme
