### ISSUE TITLE
Tensorflow Converter

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ppogg/YOLOv5-Lite#26]
Hello,

Is there any function in order to convert the Yolov5-lite models to TensorFlow?

**Comment by ppogg** [comment]
Yes, in fact, I haven’t tried this type of conversion.
As you see, yolov5-lite evolved from yolov5. You can use the whole tools from yolov5 in this repository. For example, the following link converts .pt models to .tf models. 
`[https://github.com/ultralytics/yolov5/issues/4586](https://github.com/ultralytics/yolov5/issues/4586)`
You can have a try and I guarantee that it is also available in this warehouse. If you have any questions, keep communicating. Good luck! My friend!

**Comment by AlexisPapaioannou** [comment]
Thank you!

**Comment by JNaranjo-Alcazar** [comment]
Hi @AlexisPapaioannou did you get it? Could you convert the model to TFLite?

**Comment by AlexisPapaioannou** [comment]
Yeap, but only for the supported functions.

**Comment by ppogg** [comment]
[https://github.com/PINTO0309/openvino2tensorflow/issues/82](https://github.com/PINTO0309/openvino2tensorflow/issues/82)
It include all the tflife model, like fp16, fp32, int8
