### ISSUE TITLE
Which model is the fastest?

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ppogg/YOLOv5-Lite#27]
I wonder which architecture inside the model folder corresponds to the fastest (yolo-fastest) indicated in the README repo.

I mean, what command should I run in order to train that network?

Thanks in advance!

**Comment by ppogg** [comment]
I do not understand you. Are you asking which model is the fastest in the warehouse?
If it is the above question, the answer is as follows：
Currently there is only the YOLOv5-Lite model in the warehouse, you can specify the configuration file during training
`if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', type=str, default='yolov5-lite.pt', help='initial weights path')
    parser.add_argument('--cfg', type=str, default='models/yolov5-lite.yaml', help='model.yaml path')
    parser.add_argument('--data', type=str, default='data/your_data.yaml', help='data.yaml path')
    parser.add_argument('--hyp', type=str, default='data/hyp.scratch.yaml', help='hyperparameters path')
    parser.add_argument('--epochs', type=int, default=100)
    parser.add_argument('--batch-size', type=int, default=16, help='total batch size for all GPUs')`
You can have a try and I guarantee that it is also available in this warehouse. If you have any questions, keep communicating. Good luck! My friend!
