### ISSUE TITLE
ncnn raspberry pi example

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [ppogg/YOLOv5-Lite#29]
Hi again! I would like to thank you for this amazing work.

I am trying to deploy this yolo into my raspberry pi. However, I am new to ncnn framework.

Could you provide me an example or further steps in order to follow?

Until now, I have deployed this repo in the Raspberry Pi and I have run `detect.py`, obtaining 3 second inference per image.

How do I accomplish this 100ms inference time that you report?

**Comment by ppogg** [comment]
Regarding your question, the answers are as follows:
It is best to use C++ inference on the Raspberry Pi;
How to increase the speed of the Raspberry Pi to the maximum: [https://github.com/ppogg/YOLOv5-Lite/issues/14](https://github.com/ppogg/YOLOv5-Lite/issues/14)
And the compilation and installation of ncnn: [https://zhuanlan.zhihu.com/p/368653551](https://zhuanlan.zhihu.com/p/368653551)
The above blog is base on window system, the arm platform is similar
In addition, I think using python to perform inference under 640*640 input, the speed about 1-2s is the most normal
