### ISSUE TITLE
where is "layer.h"

### ISSUE THREAD

**Issue by aimen123** [ppogg/YOLOv5-Lite#30]

**Comment by ppogg** [comment]
ncnn demo是需要你提前在自己的电脑编译安装好ncnn，然后将yolov5-lite.cpp放到ncnn/example里面，之后再重新make一遍即可运行

**Comment by ppogg** [comment]
layer.h、net.h等都是ncnn的头文件，此处不提供，ncnn编译包中是有的，只要编译好ncnn即可

**Comment by aimen123** [comment]
大佬恢复速度真快，新手，谢谢，找到了

**Comment by aimen123** [comment]
大佬回复速度真快，找到了谢谢
