### ISSUE TITLE
What happen with my yolov5.param file ?

### ISSUE THREAD

**Issue by Houangnt** [ppogg/YOLOv5-Lite#31]
I try to convert your yolov5-lite.pt in folder weights to get 2 file .bin and .param
![image](https://user-images.githubusercontent.com/48252530/134886017-738c3a6f-7ba7-416c-856a-f591461c1de9.png)
When i open file my yolov5.pram after using ncnn, I have seen the difference from your yolov5-lite.param file on assets folder (ncnn_Android). This is my yolov5.param:
![image](https://user-images.githubusercontent.com/48252530/134886541-33103bec-a9fb-4f70-a098-6d85e7a9a37e.png)
What step did i go wrong ?

**Comment by ppogg** [comment]
God, my friend, you seem to make a mistake when extracting the onnx file.
Please provide your onnx file, I will help you troubleshoot the problem

**Comment by NTHoang99** [comment]
> Please provide your onnx file, I will help you troubleshoot the problem
Here:
https://drive.google.com/file/d/1E2NAngsRld6e3VFBNXQOQMOn00uuTL4f/view?usp=sharing. Tks so much

**Comment by NTHoang99** [comment]
This is way i convert onxx file on google colab ? At what step do i need to edit or add ?

**Comment by ppogg** [comment]
> This is way i convert onxx file on google colab ? At what step do i need to edit or add ? I saw some guide to convert using ncnn framework, I find them put the line YOLOv5 Focus to use Yolov5 model - Is this really necessary ? Because i find you did'nt change it. https://colab.research.google.com/drive/1aZBkDK23EF5LmOsDWUpulAlimPJOI5Q6?usp=sharing

Yes, if you need to use frameworks such as mnn or ncnn, please be sure to remove the focus layer. I think they are not useful for the chip

**Comment by NTHoang99** [comment]
> > This is way i convert onxx file on google colab ? At what step do i need to edit or add ? I saw some guide to convert using ncnn framework, I find them put the line YOLOv5 Focus to use Yolov5 model - Is this really necessary ? Because i find you did'nt change it. https://colab.research.google.com/drive/1aZBkDK23EF5LmOsDWUpulAlimPJOI5Q6?usp=sharing
> 
> Yes, if you need to use frameworks such as mnn or ncnn, please be sure to remove the focus layer. I think they are not useful for the chip

I try to optimize .param and .bin But I don't think it's right. Why ?
![image](https://user-images.githubusercontent.com/48252530/135055840-406d52f1-07fa-4238-b767-52f155a53c23.png)

**Comment by ppogg** [comment]
This is converted from your onnx file, have a try, friend
param：[https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing](https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing)
bin：[https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing](https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing)
 I think there is no trouble with your param files and mine, one is fp32 and the other is fp16, as long as it runs without errors.

**Comment by NTHoang99** [comment]
> This is converted from your onnx file, have a try, friend param：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing bin：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing I think there is no trouble with your param files and mine, one is fp32 and the other is fp16, as long as it runs without errors.

Can you turn on public sharing ? :v

**Comment by ppogg** [comment]
> > This is converted from your onnx file, have a try, friend param：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing bin：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing I think there is no trouble with your param files and mine, one is fp32 and the other is fp16, as long as it runs without errors.
> 
> Can you turn on public sharing access ? :v I have a question. I trained model with yolov5s and I'm wondering if I can convert it to put your's code ? Because i find architechture between Yolov5-lite vs Yolov5s is not same, Does It effect on speed on android device ?

yeah, the speed difference between the two models is about 5 times, yolov5s can't detect in real time on low configured phones

**Comment by NTHoang99** [comment]
> > > This is converted from your onnx file, have a try, friend param：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing bin：https://drive.google.com/file/d/1pzJi98gefN5JiRtppDGm0gW2YGFBkDkY/view?usp=sharing I think there is no trouble with your param files and mine, one is fp32 and the other is fp16, as long as it runs without errors.
> > 
> > 
> > Can you turn on public sharing access ? :v I have a question. I trained model with yolov5s and I'm wondering if I can convert it to put your's code ? Because i find architechture between Yolov5-lite vs Yolov5s is not same, Does It effect on speed on android device ?
> 
> yeah, the speed difference between the two models is about 5 times, yolov5s can't detect in real time on low configured phones

Maybe, i will retrain my data using Yolov5-lite. Is this best solution ? :v

**Comment by ppogg** [comment]
Yeah, I am. There is already a pretrained model, so finetune doesn‘t take up too much time
