### ISSUE TITLE
Light_C3 function

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ppogg/YOLOv5-Lite#32]
Hello,

Is there any update about the Light_C3?

**Comment by ppogg** [comment]
You can use the yolov5-lightC3.yaml for training directly. The effect is not good, and the map is reduced by about two points, but the parameters and flops are less

**Comment by AlexisPapaioannou** [comment]
Thank you, but where can I find the function of Light_C3? (I didn't find it in file common.py)

**Comment by ppogg** [comment]
Sorry, it’s really busy these days, I will update the code this weekend
