### ISSUE TITLE
想知道这个模型对少样本数据如何?

### ISSUE THREAD

**Issue by Alex866850** [ppogg/YOLOv5-Lite#4]
大佬,想问下这个模型对少样本数据集的训练效果如何,我这边数据集量太少,对速度也有要求,所以想问下?

**Comment by ppogg** [comment]
是的，对于特征明显或者易区分的待检测目标，shufflev2-yolov5s还是很鲁棒的，此为训练水果的数据：
![050](https://user-images.githubusercontent.com/82716366/130254645-a9eb3363-1287-4b29-a772-10e256dfc655.jpg)
![025](https://user-images.githubusercontent.com/82716366/130254660-94754820-14ed-4bf3-a62f-ace789e1ad66.jpg)
训练数据在350张左右，如你所见，单独识别山楂，苹果，葡萄还是非常简单的，还不需要特别深的网络，但是！！如果你识别山楂、苹果这种二分类，在同一张图片上就不好说了，可能会误识别哈哈哈~

**Comment by Alex866850** [comment]
好的,谢谢,另外想问下训练小尺度目标的话需不需要增大图片的size?

**Comment by ppogg** [comment]
最好需要
