### ISSUE TITLE
关于使用c++部署的问题？

### ISSUE THREAD

**Issue by Hezhexi2002** [ppogg/YOLOv5-Lite#43]
你好，大佬，就是我想问一下如果使用trt或tensorrt加速能够用c++的api吗，因为目前我的项目其他部分是用的c++，然后用tensorrt加速yolov5用的是c++，主要是我看您这个把pplcnet和yolov5s结合的工作在速度上有很大提升，我就是想用openvino的c++的api来推理可以吗？

**Comment by Hezhexi2002** [comment]
> > > > 你好，大佬，就是我想问一下如果使用trt或tensorrt加速能够用c++的api吗，因为目前我的项目其他部分是用的c++，然后用tensorrt加速yolov5用的是c++，主要是我看您这个把pplcnet和yolov5s结合的工作在速度上有很大提升，我就是想用openvino的c++的api来推理可以吗？
> > > 
> > > 
> > > 可以的，tensorrt参考这个：
> > > https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5
> > > openvino参考这个：
> > > https://github.com/Chen-MingChang/pytorch_YOLO_OpenVINO_demo
> > > 里面有很详细的教程
> > 
> > tensorrt目前我就是使用的tensorrtx，不过这个openvino的仓库我看还是用的python的api啊
> 
> 是的，我是为了快点验证在cpu上的速度，才用的python

好吧，大佬就是现在pplcnet+yolov5你已经merge了吗，我就是想试一下效果，但是我是想用openvino c++的api来用

**Comment by Hezhexi2002** [comment]
> 代码已经merge

好的，马上测试

**Comment by Hezhexi2002** [comment]
还是只需要替换掉common.py然后用litec.yaml训练就行吗？

**Comment by ppogg** [comment]
不行哦，需要修改commond.py和yolo.py

**Comment by Hezhexi2002** [comment]
> 不行哦，需要修改commond.py和yolo.py

大佬，那具体是修改哪些内容呢？
