### ISSUE TITLE
weights folder no long supplied

### ISSUE THREAD

**Issue by prying** [ppogg/YOLOv5-Lite#46]
when running on v1.3:
`python detect.py --source sample/horse.jpg`
returns the error `FileNotFoundError: [Errno 2] No such file or directory: 'weights/yolov5ss.pt'` since the weights folder has been removed from the github repository

**Comment by ppogg** [comment]
```
python detect.py --source sample/horse.jpg
``` 
Please use v5lite-s.pt / v5lite-c.pt / v5lite-g.pt!!!
![image](https://user-images.githubusercontent.com/82716366/137689238-4192721f-530c-45c6-b1c0-8ffbb36dd094.png)

**Comment by prying** [comment]
Thanks that works now
