### ISSUE TITLE
多卡分布式训练缓慢

### ISSUE THREAD

**Issue by Songrtsu** [ppogg/YOLOv5-Lite#5]
您好，我用您的模型训练自己的数据集，大概一万左右，batch size是64，用了两张1080ti，但是训练过程极其缓慢，比单卡快了不到20％，请问这种情况是正常的吗？gpu占用率也极其低。

**Comment by ppogg** [comment]
你应该是直接用的DDP进行的分布式训练，请不要使用那种方式，性价比及其低，且很容易造成算力的浪费，请使用launch进行训练，可以将训练速度加快4倍，且利用率更高：
`$ python -m torch.distributed.launch --nproc_per_node 2 train.py --batch 128 --data coco.yaml --weights yolov5ss.pt --device 0,1`
具体请参考：
[https://github.com/ultralytics/yolov5/issues/475](https://github.com/ultralytics/yolov5/issues/475)
在四张2080ti上，640*640的分辨率，迭代一次coco数据集大概是6分钟
