### ISSUE TITLE
报错dataset not found

### ISSUE THREAD

**Issue by suhanling** [ppogg/YOLOv5-Lite#52]
...按步骤 数据格式 类别改了之后  运行报错dataset not found   是还需要改哪里的配置嘛

**Comment by suhanling** [comment]
![image](https://user-images.githubusercontent.com/66514109/138100700-a97e2107-c3aa-4484-b04b-0eb3b1a4463d.png)

**Comment by ppogg** [comment]
配置出了问题，没有读到参数

**Comment by suhanling** [comment]
麻了.... 我除了动了路径之外 然后parser 那改了一些default训练参数外就没动过了.....
