### ISSUE TITLE
使用openvino推理xml文件报错

### ISSUE THREAD

**Issue by Fraunhofer0126** [ppogg/YOLOv5-Lite#54]
我在项目根目录下`python openvino/openvino.py -m v5lite-c.xml -i openvino/bike.jpg`,  我事先运行了`/opt/intel/openvino_2021/bin/setupvars.sh`
报错：
```
Traceback (most recent call last):
  File "openvino/openvino.py", line 23, in <module>
    import ngraph
  File "/opt/intel/openvino_2021/python/python3.8/ngraph/__init__.py", line 16, in <module>
    from ngraph.helpers import function_from_cnn
  File "/opt/intel/openvino_2021/python/python3.8/ngraph/helpers.py", line 7, in <module>
    from openvino.inference_engine import IENetwork
  File "/home/fraunhofer/Software/YOLOv5-Lite/openvino/openvino.py", line 25, in <module>
    from openvino.inference_engine import IENetwork, IECore
ModuleNotFoundError: No module named 'openvino.inference_engine'; 'openvino' is not a package
```

**Comment by ppogg** [comment]
也有可能是安装和编译成功，但是引用包出了问题，代码是没问题的。另外，这个代码库用的是最新的openvino版本，版本最好不要差太大

**Comment by Fraunhofer0126** [comment]
> 也有可能是安装和编译成功，但是引用包出了问题，代码是没问题的。另外，这个代码库用的是最新的openvino版本，版本最好不要差太大

我安装和编译成功了，yolox项目目录下的demo/OpenVINO/python/openvino_inference.py 我能正常运行
版本是2021.4.689

**Comment by ppogg** [comment]
你可以试下保留引用的库，然后使用openvino.py的代码覆盖/OpenVINO/python/openvino_inference.py 的代码，看看会不会报缺库的错误

**Comment by 2050airobert** [comment]
你好，大佬
AttributeError: 'openvino.inference_engine.ie_api.Blob' object has no attribute 'output_data' 为啥我运行起来后，还是会报错，我用的是2022.1版本的openvino。 请问下，您之前碰到过嘛？也用了最新的2022.1版本吗？
多谢哈
