### ISSUE TITLE
ShuffleBlock Convert to Tensorflow model

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ppogg/YOLOv5-Lite#56]
Is there any implementation of ShuffleBlock in Tensorflow in order to convert the model in tflite for an android device? (Following the tf.py file of original Yolov5 repository (https://github.com/ultralytics/yolov5/blob/master/models/tf.py))

**Comment by ppogg** [comment]
[https://github.com/PINTO0309/openvino2tensorflow/issues/82](https://github.com/PINTO0309/openvino2tensorflow/issues/82)
you can use it
