### ISSUE TITLE
为什么不用mobilenetv3

### ISSUE THREAD

**Issue by Msyout** [ppogg/YOLOv5-Lite#6]
如题，请问大佬是不是有基于mobilenetv3进行实验？效果如何？

**Comment by ppogg** [comment]
已经做过类似的消融了。精度上和shufflev2-yolov5差不多，但在树莓派上运行要慢两倍，我还有一个shufflev2-0.5的版本，速度可以更快的，但是精度下降了十几个点，实在是不忍直视。。。所以不管是shufflev2-0.5、mobilev3，对我来说性价比都没有这个模型高。
另外，github有一个mobilenetv2的魔改版，你搜下应该有的，那个是基于4.0版本做的，实验做得很扎实，不过5.0的一些功能可能就用不了，看你需求

**Comment by Msyout** [comment]
好的，如果将mobilev3和v5l或者v5m结合，精度会不会提高一些呢？另外大佬的那个mobilev2和yolov5的仓库链接可以发一下吗？

**Comment by ppogg** [comment]
其实是差不多的，因为使用的是yolov5 head
这个是我说到那个仓库，你可以看看：
https://github.com/Syencil/mobile-yolov5-pruning-distillation
