### ISSUE TITLE
没有找到weights文件夹

### ISSUE THREAD

**Issue by liufan19960306** [ppogg/YOLOv5-Lite#62]
没有找到可运行的pt文件，drive.google上不去下载不了模型，大神是不是漏了上传weights文件夹

**Comment by ppogg** [comment]
不呢，链接刚更新过，是可以下载的，我在下午2点前会放一个model zoo的百度云链接，到时候方便你们下载

**Comment by DCC-lzhy** [comment]
> 不呢，链接刚更新过，是可以下载的，我在今天会放一个model zoo的百度云链接，到时候方便你们下载

哪里有百度云的链接，没找到，我想下载权重

**Comment by ppogg** [comment]
在readme里面，model_zoo最下方
baidu downlod：link：https://pan.baidu.com/s/1EyIcipMxX1TYmvEcSZ-Vzw          key：k7b5

**Comment by wszhengjx** [comment]
请问weitghs下载完放在哪里被读取呢？
