### ISSUE TITLE
转换脚本 scripts/rep_convert.py 重参化g模型的存在问题

### ISSUE THREAD

**Issue by Xiaoyw1998** [ppogg/YOLOv5-Lite#64]
转换脚本里使用的函数是`attempt_download`，不应该是`attempt_load`吗？

**Comment by bluoluo** [comment]
对的，但是转了感觉没差别打开看了下

**Comment by bluoluo** [comment]
确实，不过转了打开看了下，没看出啥区别

**Comment by ppogg** [comment]
感谢反馈，代码已修复，这是重参化前的模型参数和计算量、模型结构：
![image](https://user-images.githubusercontent.com/82716366/151650455-c4f55df7-d8c8-46e5-bd7f-b497f8ef5b6c.png)
![image](https://user-images.githubusercontent.com/82716366/151650493-53726cfa-99a5-4cf3-a382-80309fec6383.png)
这是重参化后的模型参数和计算量、模型结构：
![image](https://user-images.githubusercontent.com/82716366/151650418-64ff3685-26dd-433f-ba44-f6d72ed100d4.png)
![image](https://user-images.githubusercontent.com/82716366/151650379-af9833de-dfb0-43f4-9fb3-d0e325fb372d.png)
修复的转化脚本近期上传！
