### ISSUE TITLE
模型文件在master版本的yolo下面跑不起来

### ISSUE THREAD

**Issue by deep-practice** [ppogg/YOLOv5-Lite#65]
python3 train.py --data data/data.yaml --cfg models/v5Lite-g.yaml --batch-size 8

RuntimeError: Given groups=1, weight of size [3, 64, 2, 2], expected input[1, 32, 128, 128] to have 64 channels, but got 32 channels instead

**Comment by ppogg** [comment]
你是不加载模型进行训练是吗？

**Comment by ppogg** [comment]
昨晚测试了一遍，似乎未发现你说的问题，是否有更改过代码？

**Comment by deep-practice** [comment]
没有改过代码，就是昨天git clone的yolov5 master分支，然后在common.py里面把你加的模块加了进去，加不加载模型训练都是一样的报错。

**Comment by ppogg** [comment]
> 没有改过代码，就是昨天git clone的yolov5 master分支，然后在common.py里面把你加的模块加了进去，加不加载模型训练都是一样的报错。

把我加的模块都加进去？？这个指的是？

**Comment by deep-practice** [comment]
> > 没有改过代码，就是昨天git clone的yolov5 master分支，然后在common.py里面把你加的模块加了进去，加不加载模型训练都是一样的报错。
> 
> 把我加的模块都加进去？？这个指的是？

就是新的一些层，比如LC_Block，LC_SEModule等

**Comment by ppogg** [comment]
好的，已记录，找个时间确认下

**Comment by 619732457** [comment]
你好，我碰到了这个相同的错误。使用的ultralytics的yolov5，因为我已经对它做了些改进，就想把您的网络加进去。我目前先想使用v5lite-g，在common.py添加了RepVGGBlock的相关类，执行train时，报了这个错误。我想请问有可能在哪里出现了问题？
