### ISSUE TITLE
Have you tried pruning YOLOv5-Liteg through sparsity training and channel pruning

### ISSUE THREAD

**Issue by HouBiaoLiu** [ppogg/YOLOv5-Lite#66]
I have tried pruning yolov5s, and get 700K params, map only decrease 3%

**Comment by ppogg** [comment]
It's cool! Yes, I tried it, but the code was written by the previous company, which is almost impossible to open source! We open to pr, and welcome you pull request very much!

**Comment by ppogg** [comment]
It's cool! Yes, I tried it, but the code was written by the previous company, which is almost impossible to open source! We open to pr, and welcome you pull request very much!
