### ISSUE TITLE
Trying v5Lite-s.pt on a single image

### ISSUE THREAD

**Issue by kennybradley** [ppogg/YOLOv5-Lite#67]
I am trying to test out v5Lite-s.pt on a raspberry pi so I made a simple script to load the model, and pass in an image.  

When I passed in the image I got an input tensor error : 
Expected 4-dimensional input for  4-dimensional weight [32, 3, 3, 3] but got 3-dimensional input of size [3, 320, 320] instead

I thought I followed the same process in your code, model = attempt_load , model.eval(), Image.open, transform to tensor (resized to 320,320), model(image_tensor) but it looks like I'm missing layers, or there's preprocessing I am missing, or the input dimensions are wrong.

Thanks in advance.

**Comment by ppogg** [comment]
Hi，friend. I don't understand what you mean completely?？

**Comment by kennybradley** [comment]
I downloaded v5Lite-s.pt and tried to test it in a very simple script.  This is what I did to get the wrong input size error:

```
import torch
from models.experimental import attempt_load
from PIL import Image
from torchvision import transforms

model = attempt_load("v5Lite-s.pt")
tfms = transforms.Compose([transforms.Resize((320,320), transforms.ToTensor())])
img_tensor = tfms(Image.open("test.jpg"))
results = model(img_tensor)
print(results)
```

Is there something about the structure of the network that makes this the wrong way to test it?  I'm used to tensorflow so it's possible I missed a setup function for pytorch.
