### ISSUE TITLE
Output of v5Lite-s model

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ppogg/YOLOv5-Lite#68]
Which the output of the v5Lite-s model? Is it the same as the Yolo v5s ?

**Comment by ppogg** [comment]
Not all of them, you can read this blog：[https://blog.csdn.net/weixin_45829462/article/details/119787840](https://blog.csdn.net/weixin_45829462/article/details/119787840)

**Comment by AlexisPapaioannou** [comment]
Sorry, but I can find information in this blog. Is there any other link or blog?

**Comment by ppogg** [comment]
> Which the output of the v5Lite-s model? Is it the same as the Yolo v5s ?
Hi, friend. what's your mean about the output of the v5Lite-s model? Like tensor?

**Comment by AlexisPapaioannou** [comment]
> > Which the output of the v5Lite-s model? Is it the same as the Yolo v5s ?
> > Hi, friend. what's your mean about the output of the v5Lite-s model? Like tensor?

Yeap, the output tensor.
