### ISSUE TITLE
树莓派如何部署ncnn

### ISSUE THREAD

**Issue by Liaruto** [ppogg/YOLOv5-Lite#70]
你好，博主。我是一个ncnn的新手，我想了解一下如何在树莓派上面部署ncnn并做推理，目前完成了树莓派的ncnn框架的编译，但是如何进行推理呢？能不能提供一个教程，谢谢。

**Comment by ppogg** [comment]
你可以看下这个:
《YOLOv5-Lite:NCNN+Int8部署和量化，树莓派也可实时》,https://blog.csdn.net/weixin_45829462/article/details/119787840
更详细的涉及到sdk开发，cmake编写，cpp开发，估计讲起来可以写一本书，太多了

**Comment by Liaruto** [comment]
这个我看到了，但是我并不是很理解，如果只是想单纯的实现呢？有没有相关教程呢？实现Ncnn在树莓派上的推理过程
