### ISSUE TITLE
您好，model hub超链接怎么失效了呢？

### ISSUE THREAD

**Issue by Wanghe1997** [ppogg/YOLOv5-Lite#73]
另外，您的YOLOv5-Lite可以部署到jetson-nano吗？有相应的教程吗？谢谢

**Comment by ppogg** [comment]
Model hub的超链接？model hub里面的模型没有提供预训练模型哦，model zoo才有

**Comment by Wanghe1997** [comment]
> Model hub的超链接？model hub里面的模型没有提供预训练模型哦，model zoo才有

![image](https://user-images.githubusercontent.com/45507837/142722236-b4f658cc-5f9a-4cf3-8a63-df5205b1ae4a.png)
这里点不进去
