### ISSUE TITLE
v5lite-s-int8.bin file does not exist.

### ISSUE THREAD

**Issue by dankernel** [ppogg/YOLOv5-Lite#75]
I can't download the `v5lite-s-int8.bin` file in the [ncnn readme.md](https://github.com/ppogg/YOLOv5-Lite/tree/master/ncnn)

Google Drive says there are no files.
https://drive.google.com/file/d/1U4Vt6Oqa7ER0CahaMIdHcn0eagv1iOcw/view?usp=sharing 
Please check the validity of Google Drive.

**Comment by dankernel** [comment]
Fixed in #76

**Comment by ppogg** [comment]
good job！
