### ISSUE TITLE
Exporting from pytorch to onnx model

### ISSUE THREAD

**Issue by awl-anht-nguyen** [ppogg/YOLOv5-Lite#77]
Hi @ppogg @dankernel, thanks for your amazing work. I've trained yolov5-lite-s on my custom dataset using your yolov5-lite-s pretrained weight. But when I converted from pytorch checkpoint to onnx using your `model/export.py` script, I got `best.onnx` file, then I used **Netron** web to visualize converted model, I got model with 3 outputs instead of  detection one although I set `model[-1].export = True`. I inferenced the converted model using onnx runtime but got (1, 3, 80, 80, 7) output shape (i had 2 classes), so I cannot use NMS on the output. The output seems weird. Could you give me some suggestions? Thank you.
![best onnx](https://user-images.githubusercontent.com/84887915/143037988-517946eb-38b3-41f0-81da-247d54a7cef2.png)

**Comment by nghoaithuong** [comment]
Please check the line `model.model[-1].export` in models/export.py : set it to False.
It means all detection layers output will be concatenated and returned as a single output like (1,6000,6) output shape for 1 class detection.
Hope that works for you

**Comment by awl-anht-nguyen** [comment]
@nghoaithuong Thanks for your suggestion. I changed and it worked like a charm.
