### ISSUE TITLE
some errors in running detect.py

### ISSUE THREAD

**Issue by aybberrada** [ppogg/YOLOv5-Lite#82]
there are some small problems preventing detect.py from successfully running
first of all after trying **python detect.py --source car.jpg** i get **if isinstance(m, (Conv, DWConv)) and hasattr(m, 'bn'):
NameError: name 'DWConv' is not defined**, after reading models/common.py the problem i think is that DWConv should be DWConvblock. but still even if i make this change. and run detect.py i still get an error **AttributeError: 'Conv' object has no attribute 'forward_fuse'** which i can't resolve!!

Has anyone successfully run detect.py ??

**Comment by ppogg** [comment]
Wait, did you modify the source code?

**Comment by aybberrada** [comment]
thank u @ppogg I appreciate it!
i just changed (locally in my machine ofc) the 214 line in models/yolo from **if isinstance(m, (Conv, DWConv)) and hasattr(m, 'bn'):**  to **if isinstance(m, (Conv, DWConvblock)) and hasattr(m, 'bn'):** . seems like it solved the issue but as i said there r a lot other ones

**Comment by zlszhonglongshen** [comment]
> there are some small problems preventing detect.py from successfully running first of all after trying **python detect.py --source car.jpg** i get **if isinstance(m, (Conv, DWConv)) and hasattr(m, 'bn'): NameError: name 'DWConv' is not defined**, after reading models/common.py the problem i think is that DWConv should be DWConvblock. but still even if i make this change. and run detect.py i still get an error **AttributeError: 'Conv' object has no attribute 'forward_fuse'** which i can't resolve!!
> 
> Has anyone successfully run detect.py ??

我也遇到了这个问题，

File "/home/johnson/projects/detection/YOLOv5-Lite-master/models/yolo.py", line 214, in fuse
    if isinstance(m, (Conv, DWConv)) and hasattr(m, 'bn'):
NameError: name 'DWConv' is not defined

**Comment by 98765mm** [comment]
我也遇到了相同的问题

**Comment by ppogg** [comment]
已修复此bug，请尽情享用它！

**Comment by aybberrada** [comment]
@ppogg thanks man! btw i think line 212 should also be **m.forward = m.fuseforward  # update forward**. other than that it's 100% working 👍

**Comment by 98765mm** [comment]
> 已修复此bug，请尽情享用它！

AttributeError: 'Conv' object has no attribute 'forward_fuse'

**Comment by ppogg** [comment]
已修补此漏洞，请重试！

**Comment by hamid-mp** [comment]
I have this issue too
`AttributeError: 'Conv' object has no attribute 'forward_fuse'
`

**Comment by ppogg** [comment]
请git clone最新的仓库代码：
![image](https://user-images.githubusercontent.com/82716366/150708252-34c747da-7149-4059-b19c-626b608ae533.png)
之前的漏洞已修复
