### ISSUE TITLE
pytorch to onnx error

### ISSUE THREAD

**Issue by gengxqa** [ppogg/YOLOv5-Lite#83]
用的是export.py代码，--img-size 640 640 ,报错
runtimeerror: Given groups=1, weight of size[60,60,1,1], expoected input[48,30,80,80] to have 60 channels,but got 30 channels instead
作者有没有什么建议

**Comment by ppogg** [comment]
你这个是第六版的v5？然后改了结构？

**Comment by gengxqa** [comment]
感谢您的回答，代码不小心被我改了，问题已经解决。
