### ISSUE TITLE
Convert onnx model to IR (xml file)

### ISSUE THREAD

**Issue by AlexisPapaioannou** [ppogg/YOLOv5-Lite#86]
How can convert an onnx model to IR representation?

**Comment by AlexisPapaioannou** [comment]
Finally, I found the solution.

!python /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
  --input_model /content/drive/file.onnx \
  --output_dir /content/drive/optimizations \
  --data_type FP32\

**Comment by ppogg** [comment]
ok
