### ISSUE TITLE
FPS a little high!

### ISSUE THREAD

**Issue by dsantiago** [ppogg/YOLOv5-Lite#88]
Hi @ppogg, firstly congrats with this awesome work....

I was trying training in a custom data from a Raspberry Camera but my FPS was too high(> 1 sec), i think i am missing something in the wild. Is there anyway to turn it better? ncnn i think is not an option(c learning curve) because i need to add more logic to the inference code(check if people are passing a specific point) ...

One thing the occurs me is that loading the video from the MicroSD disc maybe have some latency aswell...

<img width="1920" alt="Screen Shot 2021-12-23 at 01 48 26" src="https://user-images.githubusercontent.com/3484029/147189914-3f5b5794-3141-4568-8e35-9579c59cf9cc.png">

**Comment by ppogg** [comment]
You are welcome to use yolov5 lite.
If you want to get faster inference speed, See here：
[https://github.com/ppogg/YOLOv5-Lite/issues/14](https://github.com/ppogg/YOLOv5-Lite/issues/14)
Also, please use c++ library for inference instead of python.

**Comment by dsantiago** [comment]
I see, too bad the Raspberry test is still in progress as the notes says in the end of the blog post...

https://zhuanlan.zhihu.com/p/368653551

I tried the ncnn github, but cannot figure out how it works... how to convert models, etc...
