### ISSUE TITLE
repvggblock相关预训练问题？

### ISSUE THREAD

**Issue by HuKai-cv** [ppogg/YOLOv5-Lite#90]
请问这两个模型的预训练权重您还有吗？有的话可以给我一份吗？我的邮箱是：1059502393@qq.com  万分感谢！
yolov5-repvgg_A1.yaml、yolov5_repvgg_prune.yaml

**Comment by ppogg** [comment]
yolov5-repvgg_A1.yaml权重已发，yolov5_repvgg_prune.yaml权重找不到了

**Comment by SCAU-HuKai** [comment]
非常感谢，另外还想问问您，这个网络修改后的预训练权重您是怎么得到的呢？是在coco上直接训的整个检测网络，还是先在imagenet上训练backbone再训练coco？

**Comment by ppogg** [comment]
没有多余的卡，都是在coco上直接训的

**Comment by 962858249** [comment]
> yolov5-repvgg_A1.yaml权重已发，yolov5_repvgg_prune.yaml权重找不到了

请问可以发我一份吗？我自己弄的repvgg-yolov5没有效果，哭了~~~，感谢大咖，我的邮箱是962858249@qq.com

**Comment by 962858249** [comment]
请问可以发我一份repvgg-yolov5  yaml吗？我自己弄的repvgg-yolov5没有效果，哭了~~~，感谢大咖，我的邮箱是962858249@qq.com

是直接用repvgg替换Bottleneck中的Conv嘛？

**Comment by 962858249** [comment]
> yolov5-repvgg_A1.yaml权重已发，yolov5_repvgg_prune.yaml权重找不到了

请问训练result.csv能发一下吗？我自己训练的有些问题，感谢
