### ISSUE TITLE
关于model hub中的模型和预训练权重的问题

### ISSUE THREAD

**Issue by Lhj-cd** [ppogg/YOLOv5-Lite#93]
您好，非常感谢您开源的工作！
我想问一下您在model hub的图片中写到有mobilenetv2-small-yolov5和mobilenetv2-large-yolov5，但是我好想只找到了mobilenetv3的yolov5-mbv3.yaml文件，并没有找到mobilenetv2的，请问能够补充一下吗？
然后是可以分享一下训练好的mobilenetv2和v3的权重文件吗？或者能够去哪里下载权重呢？谢谢。

**Comment by ppogg** [comment]
https://github.com/d-li14/mobilenetv2.pytorch/blob/master/models/imagenet/mobilenetv2.py
可能是之前更新忘记上传了，另外，目前的model hub中的所有模型都是没有pretrain model的

**Comment by HaojieIu** [comment]
emmm  那可以上传一下yolov5-mbv2.yaml文件吗？
方便的话，可以分享一下您训练好的yolov5-mbv2和yolov5-mbv3权重吗？谢谢
