### ISSUE TITLE
How to convert custom trained .pt file to ncnn/mnn?

### ISSUE THREAD

**Issue by foemre** [ppogg/YOLOv5-Lite#94]
https://github.com/ppogg/YOLOv5-Lite/tree/master/ncnn this has no build instructions, I don't know how to convert .pt to ncnn

I tried converting to MNN using https://github.com/techshoww/mnn-yolov5 , but it requires .pt file to be converted to ONNX /TFLite/etc. I also tried converting my custom trained .pt to ONNX first, then converted the .onnx file to MNN. I followed all instructions in your repo. Running `./yolov5` gives me this error:

`terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

**Comment by ppogg** [comment]
1、Generally, resize errors are caused by reading out the image. Check whether your program reads the image correctly.
2、You can use the v5lite-s model of the warehouse to try to reason first. If there is an error, it should be a compilation error of your tool.
