### ISSUE TITLE
Picodet关于neck最后一层的问题

### ISSUE THREAD

**Issue by Alexsdfdfs** [ppogg/YOLOv5-Lite#95]
![image](https://user-images.githubusercontent.com/89771505/147800155-f8df7a8d-3d36-4fc0-8e7b-3f14e18348f1.png)
大佬，请问一个问题，最后一层的输出应该是ADD，不是Concat吧？

**Comment by ppogg** [comment]
好的，已接收此反馈，今晚更新模型代码

**Comment by ppogg** [comment]
已更新！
