### ISSUE TITLE
MNN v5-lite-s drive link not working

### ISSUE THREAD

**Issue by vk1996** [ppogg/YOLOv5-Lite#96]
Drive links mentioned here are not working. Please  update the drive link at the earliest

https://github.com/ppogg/YOLOv5-Lite/tree/master/mnn

**Comment by ppogg** [comment]
Hi, what do you mean by the expiration of the mnn driver?

**Comment by vk1996** [comment]
Hey. The drive link mentioned here https://drive.google.com/file/d/10dBsY0T19Kyz2sZ4ebfpsb6dnG58pmYq/view?usp=sharing to download yolov5-lite model for MNN framework is not working. Unable to download the model files

**Comment by ppogg** [comment]
[https://drive.google.com/drive/folders/1mSU8g94c77KKsHC-07p5V3tJOZYPQ-g6](https://drive.google.com/drive/folders/1mSU8g94c77KKsHC-07p5V3tJOZYPQ-g6)
[https://drive.google.com/drive/folders/1PpFoZ4b8mVs1GmMxgf0WUtXUWaGK_JZe](https://drive.google.com/drive/folders/1PpFoZ4b8mVs1GmMxgf0WUtXUWaGK_JZe)
try again please~

**Comment by vk1996** [comment]
The link is now working and I have downloaded v5-lite-s and v5-lite-int8 models. Sorry for the late update as I don't have access to the remote raspberry pi over the weekend.

The MNN model inference time is around 1500ms on raspberry pi4 model B  armv7 32-bit Linux. Any advice for best performance on my raspberry pi4 model B ?

**Comment by ppogg** [comment]
The latency is too high. In fact, you have to do the following to have a faster reasoning speed:
Use mnn or ncnn
320 resolution inference
Fixed frequency to 1.5Ghz
Use a 64-bit system (this is twice as fast)

**Comment by vk1996** [comment]
I'm using 

1) MNN (cpp_demo in this repository)
2) Input size & Net size is changed to 320
3) Max Freq is 1.5GHz and Min Freq is 800MHz
4) aarch64 Linux

Still, the inference time is nearly 1500ms . Am I doing anything wrong?

**Comment by ppogg** [comment]
The 64-bit system:
http://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/
