### ISSUE TITLE
Unsupported slice axes !

### ISSUE THREAD

**Issue by zqin1998** [ppogg/YOLOv5-Lite#97]
在转换up的v5lite-s.pt中到onnx再到ncnn，在最后ncnn出现了Unsupported slice axes !这个问题
查阅资料都是显示的是因为Foucs模块中出现的slice 操作，但是在shufflenet中并没有啊！
将onnx模型显示，确实发现中间有slice！这是怎么回事？和torch版本有关系吗？

**Comment by zqin1998** [comment]
![1](https://user-images.githubusercontent.com/83708379/147907000-3f74b5d6-9ec7-47df-8856-bca3676fd2a5.png)
![2](https://user-images.githubusercontent.com/83708379/147907006-27d1eea3-2717-469d-abf7-68016dc61fdf.png)

**Comment by ppogg** [comment]
目前我们未遇到过这种情况，因为v5lite-s的模型已经摘除掉了focus层，正常转化是不会有以上问题，你可以发一下你转化后的onnx文件，直接贴链接或者到交流群都可以，我帮你看看

**Comment by ppogg** [comment]
关闭该问题，若有新问题，将重新打开
