### ISSUE TITLE
Win10 下 Pytorch->onnx->ncnn后推理结果和Pytorch推理结果相差很大？

### ISSUE THREAD

**Issue by SCAU-HuKai** [ppogg/YOLOv5-Lite#98]
pytorch推理结果：
![3ON}WI$ YH8WZDOPQQLCQD3](https://user-images.githubusercontent.com/68494594/148395372-5425d838-3a00-47e3-b600-375d45be1921.jpg)

转成ncnn推理结果：
![WX7%RXDFR2UK@YRY22G52FF](https://user-images.githubusercontent.com/68494594/148395481-6de411f5-a03d-4530-9a2b-e26ae05ce9b5.jpg)

请问大佬，这两个差别这么大， 可能是什么原因造成的呢？

**Comment by SCAU-HuKai** [comment]
用的代码就是您的v5lites  和  cpp_demo/ncnn/v5lite-s.cpp

**Comment by ppogg** [comment]
训练的时候是不是改过anchor？
cpp的anchor对应改过来没？
最好用20210525的ncnn版本，其他版本我暂时没试过

**Comment by ppogg** [comment]
此bug已解决，关闭该问题
